-- Generated by upsert-supabase.mjs — idempotent upsert of curated demo data
begin;

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('cafe-apartment', 'ChIJP4LyNAAvdTERp2XLe0QvLeU', 'The Café Apartment', 'Chung cư Cà phê', 'food', true, array['cafes','views']::text[],
  'Nguyễn Huệ, D1', 'Nguyễn Huệ, Q1', '42 Nguyễn Huệ, Street, Sài Gòn, Hồ Chí Minh 700000, Vietnam', 10.7740888, 106.7040596, 4.4, 1795,
  null, '60k₫', 60000, 60, 120,
  'Nine floors of indie cafés in a 1960s apartment block on the walking street — every window is a photo.', 'Chín tầng quán cà phê indie trong chung cư thập niên 60 trên phố đi bộ — góc nào cũng chụp ảnh đẹp.', '☕', '["Monday: 8:00 AM – 11:00 PM","Tuesday: 8:00 AM – 11:00 PM","Wednesday: 8:00 AM – 11:00 PM","Thursday: 8:30 AM – 11:00 PM","Friday: 8:00 AM – 11:00 PM","Saturday: 8:00 AM – 11:00 PM","Sunday: 8:00 AM – 11:00 PM"]'::jsonb, null, '+84 969 111 284', 4, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'cafe-apartment');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJP4LyNAAvdTERp2XLe0QvLeU/photos/AWCwydiERPQDNFEcPMSwCv6lO350qp4z-WMNoUSTz2SnJKL89ROB_lun3uF4tp41stIW5A_ZKjJqPo6r_DHaLNAtS2i6NscGBLbDAajELnu-9wTH8S1_xirJpZi6W3LZx4monkqHmXgbJ97ToTsywgQYaKvqstWVYjkNgWgYzFijgPmQdtCKOp2-h6No_XJeRX-4uFgDLvsGoTlEHnZwdoKH_DgRtWH4h6KQ3GB8ast0-tGfOfmghiBtly0TTEovYNO7Fk0_f70IwlXUyAFLAY5gfsIrXafoEnq183z7eA1UVBZQV4yRRk0ip8XjuUmZ8WrPPw4n6PyhLYM5hAwpgCgXRU51T57wcM_Glu7NseVUOsQbpQ8AiwFIpsbHgN9WgCAmYT3gjts3RRlMEKglD5M_gsi-OgAn7s5X-KJIks9FNKmrljP8lF1_-WbRUDQqnPKJ', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDMxsPAbBBZ2d466X8dw6ImFpJX0NqTYgqOGx7rdNI53sNlFbsFv1pIzZBBvCHOuKlA6UzAGAQeFcjthl_Da0-oERFHQg_PRzkgJX7qFCXzTKNZ1y3BxRKMbT__7Gxcd9D7YdAc7kRcNmXkSLrDFUjLpg=s4800-w800', 4800, 2700, 'SHREYAS', 'https://maps.google.com/maps/contrib/100165939680759656657', 0, true
from places where slug = 'cafe-apartment';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJP4LyNAAvdTERp2XLe0QvLeU/photos/AWCwydgG1UXM8metyRDh30KI4CMl07_RJRG4Vi9fRvDRllNODq9f1za6_psEyOBBvzhBlxLs9BYgUsXIoKRRhX0HpXbCG9i9I2e9AHRpf8bIi8eD8rl2XoN8zawTnM86ntaENrz6IvS72Sk7M0OAETW25hYJFB-wNTMjZIRLKFmg4ZTiBBtvULhi-IhkrjuGn17p36m9Z6LfEFqiP70zBLEfdA6XsrGJvFT37DKJAll7Qil7DvuXJ23TZEGfTPEPovyz-ngQsEOw0AHKNHCITXiLWtbuYJJMpFbk8ACNHzeQXx53BwE4GPWxBby7inOvEPQMJ859-pbBxO4eEDFHGnVk4Z-_LeLIDx-_3ouHveSc3FEo3LUd9a-JUuS_zs_ODcxHj25eKrWngIptYoo4hgI2-tTdcyEQamkKowAhTF3Tbbw', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBSoYdKuQHEnw8tmf5zbHkrSaRWwu1811V0pny0s4zaRTMT6IB_wzQ8uo1F1Gt0Rv-6mdjGfeIru1So68xkNhH5FcGz-WjuD9PCvDwqMgJF05SD6hiJ5EX1Wlo_hEG8Kmy-7so9Mg7g-YYR=s4800-w800', 4080, 3072, 'Thitiluck Thitiluck', 'https://maps.google.com/maps/contrib/106352847400815514261', 1, false
from places where slug = 'cafe-apartment';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJP4LyNAAvdTERp2XLe0QvLeU/photos/AWCwydg2fTA2ddNF5-DderZn8vnGqOIOTCmg3Uo4G31KVDAUO4EvfwMwH9KmhUR3jVzdmJgpKU0LWd4jQOUFu-CIXoITWR2ulWpZTp6fUqsThV97y8Rr4GAFKYIBY_Fx7WqIwKx6SoGIHITehSxe3nvLwOcaPMBVXSdm5FmM4gP9HGF-uGBvaAH6BPSnR-AYt6IC1qA-vMW7J5PTQoGZLDviOX7tofa4CarAUoHC-GIgoLjYHxLbcv0-v6HN2jXTlyB3Xtd12E6gHZaUH-OhSewLSl-ngMyvh6824eXZSuPfRAIXnzk5lZVgHzjFR4IDpo4NNqoP_bA_6QJ_JM2dOokDR8y75yAwi70K4AVO18GPbcHC57MmtRq-4jSX9H719UiN8UtF_3vWqJVWgy342w1cFJRlobuAyyO7ktJAZZvugcqqo48ss0HnQ1ZdqcIn3Q', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAG_WaAwFwBzEwWGMjRVJRVAmEKB-6JsRC2whITq4Hgi352lLTV6ZhkR7EHNF6mVoDBXs5XcI4Xp9kbR7o6J0IuZqtygqGnHCpAhu9otrS5E2Z2olgiIo4WjWwYXbKcD6L2DtyO24cBixUq4jYtD9Gs=s4800-w800', 3024, 4032, 'Vishwanath Gaitonde', 'https://maps.google.com/maps/contrib/117883956379755581918', 2, false
from places where slug = 'cafe-apartment';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('workshop-coffee', 'ChIJdyfroEYvdTER2m7eTz44Bns', 'The Workshop Coffee', 'The Workshop Coffee', 'food', false, array['cafes']::text[],
  'Ngô Đức Kế, D1', 'Ngô Đức Kế, Q1', 'Tầng 2, 27 Ngô Đức Kế, Sài Gòn, Hồ Chí Minh 700000, Vietnam', 10.7734764, 106.7056037, 4.4, 4093,
  'PRICE_LEVEL_MODERATE', '90k₫', 90000, 60, 90,
  'Industrial-loft specialty roaster above Ngô Đức Kế — single-origin pour-overs and big tables that fit a whole crew of laptops.', 'Rang xưởng specialty phong cách loft trên lầu Ngô Đức Kế — pour-over single-origin và bàn dài đủ chỗ cho cả nhóm.', '☕', '["Monday: 8:00 AM – 8:30 PM","Tuesday: 8:00 AM – 8:30 PM","Wednesday: 8:00 AM – 8:30 PM","Thursday: 8:00 AM – 8:30 PM","Friday: 8:00 AM – 8:30 PM","Saturday: 8:00 AM – 8:30 PM","Sunday: 8:00 AM – 8:30 PM"]'::jsonb, 'http://www.facebook.com/the.workshop.coffee', '+84 28 3824 6801', 3, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'workshop-coffee');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJdyfroEYvdTER2m7eTz44Bns/photos/AWCwydjdk0uByo9JB-rS_FfXm62AWBGGd9wlv2BOWGoD6qxq_37d0-jhWQMlh5bSbSzLGWy-Xz4UIzIqJbt65V4hTYoVygTCJKwKzRvbd-oHC1DHcxME98QgcVlda8gG_-DOfHr91lWHsUJ8ERi-UsOCUWB26ada3llB3JDVZRYaYDTq3r2vVNhiq_DncpwiV1vGopuKKxo7ep4HUcmitJNEXL83slRBYs8DdMAERbKhAx71HZyUbrxFWmQaxN_ARWn-4CSv0MQ-mLRdzhP96Kvozad-DwvY-TVuPJ5fYX0nw7PBw6skBNwgFW0nL-p2P2UE1931Fu0ApTPxtvw14lW1eMs-gLSpbeXXGIVdwdj3WLOvOL2OK2aNH8NmgoQuflWSvyRktZXkglgYdNGp9N8rOV6PgZ66bJyQoIlSh4kyUa4j2g', 'https://lh3.googleusercontent.com/place-photos/AG9NLjC_qS63GV8q7ceM8uxyFmh8o5Udefo2Zsv3RuV24a85ZCyAEmGNHeDEM8e-Y5czXbYfbUL9X-ohWe5eCobrmD69PX5SIGKa8bRIm0YYEzpdC-Iz3Iv3lMwJ04dBOqFPBTRG6PyyzWw241CHeg=s4800-w800', 4032, 2268, 'Khánh Pro', 'https://maps.google.com/maps/contrib/105952862646285956877', 0, true
from places where slug = 'workshop-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJdyfroEYvdTER2m7eTz44Bns/photos/AWCwydh5Abo0vY_5IO1BgjGnPjVzfm1t3yBbHQ78xI8Sa4fJ8k4TtRqzC0AXukkqlnOd9tn0X2hrD5ye3KjEsj9IMP-RdPQxjpgyxhvWzIAydWiANGe2jSHfKSDXrKe7XKpbCt9VJcX2T8t6yO6VHH4LJxGDYJ9Y_LR6YCElusHZbKYKPsbOk2ZZG__nOxrqKEOJm1lZKpzJMCZBA_qGhG8Gjae7ff7whTmRXnNDRY2VJcVLghWIMsyutme27a5oA6Fk9dAaGBs6mcZEH4h1u0wJY-tcIwzBk85P5q_S8GJYXImeBTkQ9C9TnCXAfU8PmEdYE35LpkQgceWVInmatJzV7arxB_tuDzCSeY27RpqI_REDL7YtzL6va2SxZV2lbZnxSW4zhdTGDPJW57AKF6WkTLKUmGw3dj5xIUmrh7nZNYR1v-XH1QIEWtDQonsJ3yh0', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBaHZOJ6iUgS-X4OFSFu_NXwwGL-hT_7bNr065Chdtms0mAwkNLqiASZS4a28VlfOjkh6FEl1pJHLt9z5JgatKeIPVPXscZcuyHajrSgeeMxFgXR-eVFLiVxOyjCE4FylelRdcjMmbB93Ha-lPKr6zbJw=s4800-w800', 1920, 1127, 'Skipper', 'https://maps.google.com/maps/contrib/113286270576889883328', 1, false
from places where slug = 'workshop-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJdyfroEYvdTER2m7eTz44Bns/photos/AWCwydjIQsa2eN2r8r1Z9-3nMpmQUvEw2y1jV_AT_rfFh7KkZr4YfMEd2v-rm9PnOiJfAvakOdiHEaJG3a_jErUzISGiMaR_R2epx--hZ5kRTsW3WZO8vThwg-crxIMgqAB7RlfoOxIVIraNr-mhapGontWT61_HOouIiiS5s82_DICFAnLCRbp_VOmetly5AlmuJL6RwDJcQc_sRhOheYus8KZsic3sRLDeUgv7bo9wxZA4aMQp6bfIzlSPyB0-4-wOkIf61hwyVnaTAb6S6E-E4srlMxZ4rlJt1GHK8TdyKOKGVY2USqmD1V2BnXyTuO_zA0pUM8V7Y-_715MMlWQ-VD0M-vWt3v8I3oiIzkH5fK8WZ52sEFxeQF4a60LMEE6fTM30fBiG1kpk-jg1JjzFBrovYTzh-rHPZUJt32Z03hr4xNUi', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDjZFx0xiW4mj9xcpGGerVWNlrhsp8LK5P2HxUNYSctmn1fLiOpnlvoHMwBG2p58RRvM5pu5CnVFxqELrvfENUj8GrTkc33ePjb06jBOeBfIDbxOW2CLDNH4VK1Pucwwmr4WnxwVH1D40FsM5w=s4800-w800', 4032, 1816, 'Thai Binh Nguyen', 'https://maps.google.com/maps/contrib/117799904479038638737', 2, false
from places where slug = 'workshop-coffee';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('cong-caphe-dong-khoi', 'ChIJh2KS2EcvdTERReyAHhqw6vo', 'Cộng Cà Phê (Đồng Khởi)', 'Cộng Cà Phê (Đồng Khởi)', 'food', false, array['cafes','chill']::text[],
  'Đồng Khởi, D1', 'Đồng Khởi, Q1', 'B3-10 Vincom, Đồng Khởi/72 Lê Thánh Tôn, Sài Gòn, Hồ Chí Minh 700000, Vietnam', 10.7780202, 106.70199009999999, 4.1, 469,
  'PRICE_LEVEL_INEXPENSIVE', '55k₫', 55000, 45, 90,
  'Retro subsidy-era decor and the famous coconut coffee — an easy first stop before wandering Đồng Khởi.', 'Không gian bao cấp hoài cổ và món cốt dừa cà phê trứ danh — điểm dừng dễ chịu trước khi dạo Đồng Khởi.', '🥥', '["Monday: 7:30 AM – 10:00 PM","Tuesday: 7:30 AM – 10:00 PM","Wednesday: 7:30 AM – 10:00 PM","Thursday: 7:30 AM – 10:00 PM","Friday: 7:30 AM – 10:00 PM","Saturday: 7:30 AM – 10:00 PM","Sunday: 7:30 AM – 10:00 PM"]'::jsonb, 'http://congcaphe.com/', '+84 911 811 162', 2, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'cong-caphe-dong-khoi');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJh2KS2EcvdTERReyAHhqw6vo/photos/AWCwydgrk7huac34UMYe1TrHefxWNwm2y-_cDHCpBUTVtAKOx1RQd844KtaK7JJrZMHKo5YX3LOJtNaF_vKYB3ftLOS1B0a_pqAjiMBOLB0Yxy1ZIyGs41AYYhzD_hGtDyngLGiZIcLo3s_RxmblKmEV3VlnVi8hPkDu0tr2QLtxeM-6KDCQQoGcI-ioan5mNFOf6Xs4wIU2C19WXXIt7KP2DoXEoV2Nt5mk65J9l0h53trDvMjR9vw23-I6F7tLKz83EDnYN2cTOAhXRxf4EunG40fzq3lrVl18UKbngX5FQVbpByBKjqNoGBTNt6xZE9MzwbrhYvp4ww1xqAkyX_whQH27J4M5D9MWPSeUZnU_RolfSvm6bxDT6OPO0xO66W9LU8DhyNdkFERt1iKNzTzhbcuO5PzqCW04p1avSV1jyALVWHPJ', 'https://lh3.googleusercontent.com/place-photos/AG9NLjD182iuIPIm48J97kD0zIXSnEVJ9VIUJ0GUOi-ZFZIUTIwSQ6l16dyg1IikZ7H8dHAVv2OE23lIPK7fw6UDBoH7FCP79pDHzdwO2-VZL7KttJTb3CapkkxtPLWU-JlEpvZ-pTMB8TSeHp_julw=s4800-w800', 4800, 3298, 'Cộng Cà Phê', 'https://maps.google.com/maps/contrib/104225104840781833788', 0, true
from places where slug = 'cong-caphe-dong-khoi';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJh2KS2EcvdTERReyAHhqw6vo/photos/AWCwydgHm6teULtLVPvkEG5tQdpBM6TG_n-JvkMNNGmegbri8_5rj4bAxhVdeZE2ATdEr3UzJFPW-fqzIkZqLeKgPGcGdJn8Qp4q7Z3xDERmJhmAjpIA-5gR_eNf4uaSIgRscElaVGTlq_dRfmdZJU45dknqow4HHWnTHsi7ToPadlRCOe0MBHlNNvzQqgXLBuaHd2_zYc7Dheg4y74gFAEmNNqzj0A5QcyYpQPMcFF58qfqeNxIYlVbLhDuzvIpppnRRYMkXmNPE9mYwFv6Rkay8UzHQCviIF93lhZGYYexy667m7u_hfQAIwCvce968taRvSy5yLIVLX7ojnzShKuAlcPaabjpjROhxU5MKNFQ0FUeBLyVIsh904vE3KR67Q2a3aAMQsOsh7UnhYiHrT8qZ7bsvn5GLy2Qu7ZxM_RuK7cwDlEx', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBcGTBWiXB9XY7bCqZYpBvaQjpEA5ixggjh_hKf0KF4Q-cJqk1P0CYeJxyMcl_cIjfJssNvYgmjU5iJb_LnqAxXuw-iidlY9Tc6yrUKdSUCwJA9UcjIIYqglMGMyZTbDmgpcfXANL3p7jv4PRw=s4800-w800', 3600, 4800, 'Cộng Cà Phê', 'https://maps.google.com/maps/contrib/104225104840781833788', 1, false
from places where slug = 'cong-caphe-dong-khoi';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJh2KS2EcvdTERReyAHhqw6vo/photos/AWCwydjBFYEKjHzb9pIYZd_DnltmCiCEG5SVe88idtzV90Ald1275n56QELShLpURISYyY10egtH1MYBWshYpFng82TBMRxyK4ZCdvENFIjtLv_tqeuuUA-g3t6YBVZbuyA1KynFrOYXq9LfxLytgWmZqWQD3RFYI5pxrcJLK63tIv75OzJOgOOiBHbueIPC3jtqONUgXQ0ZXNuhEU6sWooEyFYqqhWf_7tbLLy6q0g8TlzEqlDCqTxL4vnDnJYqw3S8usf2ZEn7l8CdQwknujMFshMd155ds5Pn4Y7L-P9xCZLDNHprKq4KRl5WqhOql-tA6QU1vgP8Dx1I9hs_YbtrCmuXPen6zQHO2U5rKoyi1HXI73tHiXBk7K8qHsV14bGudB9sPzyFfcAtknsQEFuQE5NY-o5FZwbHp13jiu_aje-alMAQffObyDAE1dvE3nru', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDcpFsIHttdb4lGdwRGSdoLqUqshJ_CfFDOaJmQdQO-QhGh6M6M5B3kiYDb5jrlandXpKUgPAp7tKywOTiV97VCcgBnczhJsov5RcR1x0_uflqrvztW3goyxOAahWULFwajhJmN_SesWee6G7UhN16_Bw=s4800-w800', 3072, 4080, 'Long Ho', 'https://maps.google.com/maps/contrib/110854011937575254013', 2, false
from places where slug = 'cong-caphe-dong-khoi';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('little-hanoi-egg-coffee', 'ChIJqZ7MThYvdTERh6VZ5ryLuDk', 'Little HaNoi Egg Coffee', 'Little HaNoi Egg Coffee', 'food', false, array['cafes']::text[],
  'Phạm Ngũ Lão, D1', 'Phạm Ngũ Lão, Q1', 'Yersin/119/5 Phạm Ngũ Lão, Phường, Bến Thành, Hồ Chí Minh, Vietnam', 10.7694043, 106.6960112, 4.8, 5507,
  'PRICE_LEVEL_MODERATE', '50k₫', 50000, 45, 60,
  'Hanoi-style egg coffee whipped to a custard — hidden down an alley off Phạm Ngũ Lão; go early to grab the balcony seats.', 'Cà phê trứng chuẩn Hà Nội đánh bông như kem — nằm sâu trong hẻm Phạm Ngũ Lão; đi sớm để giành chỗ ban công.', '🍮', '["Monday: 7:00 AM – 9:30 PM","Tuesday: 7:00 AM – 9:30 PM","Wednesday: 7:00 AM – 9:30 PM","Thursday: 7:00 AM – 9:30 PM","Friday: 7:00 AM – 9:30 PM","Saturday: 7:00 AM – 9:30 PM","Sunday: 7:00 AM – 9:30 PM"]'::jsonb, 'http://littlehanoieggcoffee.vn/', '+84 869 095 345', 3, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'little-hanoi-egg-coffee');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJqZ7MThYvdTERh6VZ5ryLuDk/photos/AWCwydhbaQ6QLGojVHN2Mb_9Xv53Z94W-1dbRqg5pql4JkjlJyL9xGFd23YQpvNpNZcAGgjMYW3O8le28m1CL-SET6mpqT_lMXDt1HN6oPGtjHaCWrUhSZ0bxLdtis7nMPh7a1n4ZoBfk-4jtqF0xNpbq709MwJvjP-Y6lfm9d36Jh9OyJlvOKO5tosMkE_wBilhpyVnyVqFYYVWX-Fy350yYLMEhlcavX2JjEF5DBhZqtYOuO2JnAv9fndVWmM51APrLKL9MYHvGQoy3AZRfxPgMF9Pgy6BO8IoFpzAAekACvv3xNn-z4YcbRlW40Y7-GaweVjw0frKCThvmGtUooIO_32_zzGl5DwCdJSolLrGAc3hDcTHmjJ1hhwK0IBpxb2O0bFODguBJn5DaqqL8TFsBUQuzpM2VZyFcE-bI_gNHMi6zRgA', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAAha0Dbqt0FIsQft4BLw8p8GM42vRA_IfH3XdDDepmMj78dS1s3KYvx5Bs-pN8l7qzdkWfD6jPe9gscqnIMlfn6eROuG-RE_h0lNFIn7l8MqlYCPKFq894Vnvkwu8Lb6ILnfhvp16a61Df_cU=s4800-w800', 4368, 2912, 'Little HaNoi Egg Coffee (Yersin)', 'https://maps.google.com/maps/contrib/107446562256909945452', 0, true
from places where slug = 'little-hanoi-egg-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJqZ7MThYvdTERh6VZ5ryLuDk/photos/AWCwydgaFTyluoxB-71PxId584mw0I4SelTO_Cgd5JwGLCoLZeXELx4ogeJAuJntDtsp7uQFFYz65B96kajHFux8dvEW9ZuW_CU-h9jQcKv6iikW998JqYfve9ox7o90FlnineevEegzINM9p0ulnz_wfr0maVw8NOGuRM27kODAleIPewYuHMSfU0UoS26J45PI95cbJnzGWsuePLPpHoSGFY-SI6gtgX8zDHtBxGkppQAM9eu1Bavjdj_752K6svu82VqlP2lxWaTrk_2zeV6zxP3h38uL5VuUFXW7T0mp_RgXADNvsLSu0_HHU4r8532Ok_96PBuGEJEsDcbUJ8A3qodNOQXYozig6EBz0fsxbLT63gX74etq4LgBark7nKqivGOSMKqCOZKaMaqpEXSDJG08weS_Cqebr4o0GdFg8RyTfxDzY-SHk9fne1nrFQN7', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDM99rvFMMMlKvqS9-vlH9Yecnadcjx7LtYZFMG_wtqlmPZd3nfDiqPsQf_4jv_OhO8s_-S_kE0vCDaOTBWKAqB88zQsZiYYQVaLMgLod4X2B-IlDFCJXVKUIdcD8YH16yPYe4qW3ovBRkmXyH-QGB0eQ=s4800-w800', 3520, 1980, 'nicole chen', 'https://maps.google.com/maps/contrib/108445574352540580923', 1, false
from places where slug = 'little-hanoi-egg-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJqZ7MThYvdTERh6VZ5ryLuDk/photos/AWCwydg65wq4Dv5p3nzepKw68KcHG324hjboL2gBqO3ZWAie0-ORrTwwa_MeTCiyju7rqfka79MxdGCrjHBfdViE7RoHnWFGkpIBBXK336RcsnSJPDdhJF0LbRG-kVpHCCrn4uVnvby3GAFnDDqFjn_YxQW1Ac-v20Tgz789T5iiXCnSNpzEDY82U7tSydJjvO_8lqX7pLS_9B5N4Xa7I6ZkFXD0HUOetAjDefNiKkNHLbeFPG9DLS7qyVtc4iBdmoJwpAsJ7zA1cpjvvQ9gjuBabNlxLf9QPOIprZwU9oooC6E4Pxu7ijWmZqb_VwX5S4bylY7rCVjC3BullHb5ibNxC4LcgCVkDSuVynAo0t_JW_m-D-xDPFuERrphMKobTct9K3lvLnLGkg7USmv_A9MbpqXEIloFR5fmPugSraLokQUekms6', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDzg9sRPAe80ipruoG-MRXzPr5PejtLJD3Uz5PAOoFYDo_GwB6VySCA6h8tZCdlMpoYf4-KNs9WV5R0hDVOJSCaG_Mali-RCk8mXWGMoFYv6i_kdNBOy5eUfPF2C2U_VW-vtrMq7nPX-M_o9i0=s4800-w800', 4368, 2912, 'Little HaNoi Egg Coffee (Yersin)', 'https://maps.google.com/maps/contrib/107446562256909945452', 2, false
from places where slug = 'little-hanoi-egg-coffee';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('okkio-caffe', 'ChIJcUtJy3wvdTERQIZ4d5vBYS8', 'Okkio Caffe', 'Okkio Caffe', 'food', false, array['cafes']::text[],
  'Lê Lợi, D1', 'Lê Lợi, Q1', '120 - 122 Lê Lợi, Bến Thành, Hồ Chí Minh, Vietnam', 10.7725195, 106.69895849999999, 4.6, 1275,
  'PRICE_LEVEL_INEXPENSIVE', '65k₫', 65000, 45, 90,
  'Moody red-brick espresso bar overlooking Lê Lợi — small, stylish, and the coffee is taken seriously.', 'Quán espresso gạch đỏ đầy chất điện ảnh nhìn xuống Lê Lợi — nhỏ, chất, và cà phê thì cực kỳ nghiêm túc.', '☕', '["Monday: 7:30 AM – 8:00 PM","Tuesday: 7:30 AM – 8:00 PM","Wednesday: 7:30 AM – 8:00 PM","Thursday: 7:30 AM – 8:00 PM","Friday: 7:30 AM – 8:00 PM","Saturday: 7:30 AM – 8:00 PM","Sunday: 7:30 AM – 8:00 PM"]'::jsonb, 'https://www.facebook.com/okkiocaffe/', '+84 848 011 118', 2, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'okkio-caffe');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJcUtJy3wvdTERQIZ4d5vBYS8/photos/AWCwydhpvusnlGToghqXAoHW9zo6Dt6oqETAAe2I5IARPXN9uCyTvSQeHuTleHc_1uP4nuv0jOrbnMgnDjKtAprbRYU10_YVwBTWlWFeWcuEXMUqFy6wK7BjHwZkafl7iXA0-jN_2rG6SuaoLnIhNc7ysSLVq_tLOcmW909nWkcOyzRo81Mh3ug-8W0M3fO_YhCf0B47brZAz37LW9GKOrRuJU-Oeoej6kLMgKwJtysjauxUfFkrctWR4kP0MEP7xmVjxMMVqrUyguw75Ugxg7h3qaeTpGp4lTFoKdcKqJG-62J9_PTDoC5hyJKw4eMhImOSMtQmgzwVwMAx0sQmwQG5sWqr7Djaaga4KXvS0UM6GA6xrDQHSURDuMvTi4bnBXt5yyzMXLqafzVvGHwdkP2NHdz7HTrw3mTNVPiBBkAPCf4', 'https://lh3.googleusercontent.com/place-photos/AG9NLjCMcifkLSmPp7uf9Nx5DLIbHpOZFx2Oq6GzuJ6zLSzcD0ZPwXBI7YWxXFu9N5m-m-ClpPOo5B2IBmKjaH2oxkmxtbYjw5N8Fpr-kK5cRFjvWviymR3SMxHWXfTEsumBk9q5FV8B2ZZ4soEi=s4800-w800', 3840, 4800, 'OKKIO', 'https://maps.google.com/maps/contrib/102038398507456509006', 0, true
from places where slug = 'okkio-caffe';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJcUtJy3wvdTERQIZ4d5vBYS8/photos/AWCwydhuV5Sws9bx0olulcpsqToLp4PsOlcLsGMyMDBQWJRsyVmMoygeJE8LoIUzwN-QYEzHiUH8Pr9cBNtE5ZmtHZIdyW3lzRlldLKXYuuWwhMmceEV8LpEVHpPmhRXiBpFQE30kCfNfU9wtQuouhzWYddJesCGV0ZgklH-aOliOeLDhAFmzjnv5BtIne-0BKeSCL9OtiPKzxIGk-4AZKMlz4tUQO-lJfGtce2QX9onwwdptT61yvQC25SU_KQzOSyxW6-OiT1IJkLIDZenEkPo32Ko00uroCrKJM4LnRC97iQNXYd2kGCPiFtupfyuNd_fXmdB3xHtY0nbvXSu2z8WPLHJimNk3J6EcGAWO-iiFFIi3StV2XY6u2tvbjSpM8Zh9zy4f1fIRKGCpQzl5fBai6zjrvwRsf66g45scdtNGRlAJVoIEJEte7C-3WusYKiw', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDShGSwgUgUnaajl3Mqe8mtubBUFKROCtq0SQs9JbkCszpyOgN348xasrSJRcjyXiV9uLp74p_Hw7y3XDyrarVVJL2y8rUB-APZsvoOHi1I9gP6v3pIA0-Uxvnb65a9AVMnBu5_auiKrHG-A9NjuoumAg=s4800-w800', 4800, 3600, 'Tri Nguyen', 'https://maps.google.com/maps/contrib/117110730234388824076', 1, false
from places where slug = 'okkio-caffe';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJcUtJy3wvdTERQIZ4d5vBYS8/photos/AWCwydhEafVindSq2pd4X06--mPrKVipbUHXj4LokdnJM60d2ryTrgnzxFciADC7lGFGdE7q96w_PZzAkFcjLGvUzCb9EKAeGKigv1vhOBBwzDJ9OZPeKmP2ji8rlFYuR4wDOD_7-2xPO3Joe8-3fHrz0bnDv2jNfx6-1q9LMUb-LiCUV0agC5E8bi3op4yl2e2cGGp4yubbJIVeUCwM13iXZMr4hhLTU78kLgA7tGSiFdMntfeJcNnWoSoDzbdQJae17SJQRYKwAN0uFh1dnuw92K7El4Rvjwt_UXSplm3cjFcrni6jaE3NXiMvBtXFZiM65NTTVPFDHF2Yp8ErOp3i1cLZQveGHDKwSifbuGMJu642cUTMb3XSJ50jlNARDB7F1ITteSDBvyc44BThAkTOKjUouGuwdCYsgWIqDXjH6w_6xItMPsSo05Y9tOqFsF5u', 'https://lh3.googleusercontent.com/place-photos/AG9NLjCoU5U5XU1a-8xQFbzkonMNvWfLloj5pF-GMZo0O0x2RkPWX5Eyo43TlvS6HtPAoez5XbS0qLcfhSTKoEQSx3BKuklUcfjQ_pMtTXhcM556ui3-xhFqCWes8VfE6nnNKQbfw7OfdbnxvAhvAM1LedmR6w=s4800-w800', 1000, 1000, 'OKKIO', 'https://maps.google.com/maps/contrib/102038398507456509006', 2, false
from places where slug = 'okkio-caffe';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('shin-coffee', 'ChIJnxOUdKcvdTER2q9wWsl22gE', 'SHIN Heritage', 'SHIN Heritage', 'food', false, array['cafes']::text[],
  'Lưu Văn Lang, D1', 'Lưu Văn Lang, Q1', '27 Lưu Văn Lang, Bến Thành, Hồ Chí Minh 700000, Vietnam', 10.7732377, 106.69906379999999, 4.6, 393,
  'PRICE_LEVEL_MODERATE', '80k₫', 80000, 45, 90,
  'Serious Vietnamese specialty beans a block from Bến Thành — order a tasting flight and compare regions with the group.', 'Hạt specialty Việt Nam chất lượng cao cách Bến Thành một dãy phố — gọi khay thử để cả nhóm so hương vị từng vùng.', '☕', '["Monday: 7:30 AM – 6:30 PM","Tuesday: 7:30 AM – 6:30 PM","Wednesday: 7:30 AM – 6:30 PM","Thursday: 7:30 AM – 6:30 PM","Friday: 7:30 AM – 6:30 PM","Saturday: 7:30 AM – 6:30 PM","Sunday: 7:30 AM – 6:30 PM"]'::jsonb, 'https://shincaphe.com/', null, 2, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'shin-coffee');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJnxOUdKcvdTER2q9wWsl22gE/photos/AWCwydipecl86Qzvw1IzfDjNdvddhFk6MVKoWu-hOC-KJWKNjS055psQah6u9_9o5t_LD9jftWb0Kpe4ucE22nQEf060cTd70t9oYRRhCyzp7Ty16kpTpnT2tsZij70mbqjbETZ6apM0iAbxNkio2bjHNihunEPOYVI2auLLgaE0CO1OOdBe8chfgrFX31UkiPs-Wxarrlw5_1N0cRnIvgkp8Cwz6PP90P4W2gpGnMwdba_FLzZ-92FLpV9Ktyt8NNhPXKXi4j3GDjtY8p-FpPxkpnPS66fufTNbZdcQHC_PGWMCG3DOf55pj8P9jdnRh9EmOnCMFGWNbkUY7ZW1vEX5VwylqyrTBJvyu8EXJC0ZJnezXFSjIyzVJbfIxqKu3dSmGFRDo0QDM1MoamFOb3hKdxnDuEQn3qk1R7i9G9CuniwWSw', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBn_JoJbSjBOJi4v2gMdEFczGgR5E6qbKc3F9-e71ShqIYAg_iUE-qNdt_4u5BPLUYFrM_nQFI_4Kn4Iy8APQjGAqROe7HwDqq7jIcic2N_O7_U53KOTCv-7MoGFZKCZYDtivlNUIF2n1egUA=s4800-w800', 1200, 1199, 'SHIN Heritage', 'https://maps.google.com/maps/contrib/101774485035792195092', 0, true
from places where slug = 'shin-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJnxOUdKcvdTER2q9wWsl22gE/photos/AWCwydjSXRj8A1i_if6lGJDMxa19p6U-BfsltQTDHu7IRhgpvDK9E3dwQJbuDt1ChPj5P1cGZTz1TPHHio7vR4_NN_tXGyAEGO0aSaF2VN7McsMCUcD6l9BDcOUEpEw7SHUqEPUc6fI0FWWbW-V9NYGQFMRPu2YKRDzADXuWVqtiok1ZEH7aW3l_Rq5bgxQb3QBSx-qdDGxL_hh-EhESoVgXJ6hLSGoqR57c0G3St-v0pf3nhOAfhWIFuDE3vfuqJ3MFTLlr1UfL3EelWhL6-j4rkIROxn1b9HcHcMB9wvL138_yV9YS5YPyKZckloBH4rkB4dsiYAPJB-J6WvbY3YpnkAzr6LasXP0VD8KfQgbuJmo0mrp9afEJs_ZQLtadZeXt0d2_VxvNRxRxoxodNJIaYEsftcpRfDFks0y5-LHuVjJh1w', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBEcMKfncb-bPfTWpOzRJcla1cNAkbeaFNXE_Vnh5aeMTjKK3XCtugRzB_gZYzJjm_VvoYk1Ppqb9LolKDzgjzWJO2nOMrGYMj8Rc3CXXVbtaSsqKkZdH08sSzb6sXlU9tw9PiuS-NWoASQTw=s4800-w800', 3024, 3025, 'SHIN Heritage', 'https://maps.google.com/maps/contrib/101774485035792195092', 1, false
from places where slug = 'shin-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJnxOUdKcvdTER2q9wWsl22gE/photos/AWCwydgnv2rmjobqFc22YCmp5MWUlq7bs--VMJ0tx8J73ljEBMGcKsyR2VU_RstuOXun0UqM1xY2sFGBHKYK22Jo9Kc-kOrThDWRLh2zZAYlkKTKk8A3WvGvhEE6ahHgVWCzCqhi_AU8nrwb2grN_Cw-idmB0o5C3STMDD0GcD0dgPjlbN7-4Hg_p3dncrkK2C0j_akqruhkI-yqGjY6tfv0wnoQjL-vTIj3xx0SsJvbciAgDvzXb6EWG09Rc-NBWPSnvpgk9mrcAKM5uUvsJSblSlxzTWLte1I-9pa-UQHBVnSw_mYiqOec6ets5e9piX81xh2QvCf9cbv5StrT-bVJINeNLbLTQ6X4NXvLNFhEg93XMe4uQ9ZThkpHv63WrOMJiygFg1h4EehodbmZFd9uVspmd7G9tq0hLCGKJdnXf6Mxlw', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAnDRU3LeOk3_UdQORiVl-XolmHNQye_O4bHKfyMCtqx-NLwtCtZp27mhryak4x3x4tXJxsGI58JidGzovJgbZM0HJLHN9tIWhGrd0TKQyhcdJdS_62YiGIgG9jiJZmjsbpX0AZep5R9HMZyw=s4800-w800', 4032, 3024, 'Nguyen Tien Thu', 'https://maps.google.com/maps/contrib/117713615599909368380', 2, false
from places where slug = 'shin-coffee';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('bang-khuang-cafe', 'ChIJo3EOrkgvdTERugtI46wHkmI', 'Bâng Khuâng Café', 'Bâng Khuâng Café', 'food', false, array['cafes','chill']::text[],
  'Thái Văn Lung, D1', 'Thái Văn Lung, Q1', '2nd floor, 9 Thái Văn Lung, Sài Gòn, Hồ Chí Minh, Vietnam', 10.77869, 106.7050646, 4.3, 647,
  'PRICE_LEVEL_INEXPENSIVE', '60k₫', 60000, 60, 90,
  'Quiet second-floor hideout with balcony light and old-Saigon mood — the anti-crowd choice for a slow afternoon.', 'Góc trốn phố yên tĩnh trên lầu hai với nắng ban công và chất Sài Gòn xưa — lựa chọn né đám đông cho buổi chiều chậm.', '🪟', '["Monday: 7:00 AM – 10:00 PM","Tuesday: 7:00 AM – 10:00 PM","Wednesday: 7:00 AM – 10:30 PM","Thursday: 7:00 AM – 10:00 PM","Friday: 7:00 AM – 10:00 PM","Saturday: 7:00 AM – 10:00 PM","Sunday: 7:00 AM – 10:00 PM"]'::jsonb, 'http://www.facebook.com/BangkhuangCafe', '+84 903 667 888', 2, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'bang-khuang-cafe');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJo3EOrkgvdTERugtI46wHkmI/photos/AWCwydhnQ6TOciblzKonF9uv9DYpZc7XA5MdOw76z8dRl5t6gKVf7Eq4Z8GcUYNB5z9ZQg-vQwWv2tKNJpCt0laPzyeZDfLfAYGz1b_s9-sLNVJMSnF5fllbUoTEcDme3AO6amuqqSVJwA1qcRofqQnsK2aHBIBRucuTI1fWNT0d2l2nUVYRzGTQIKeZsZz27fomlnb5OVcTM7gAhV240THkcrvQkUho8Yppc5o8-SZMscMIAiehkVoc2bBn-fo9wREbZOJmm44a3Bj02RgJkfziiP-KldFd9wNXftMtjdhbQrGSPGjdHiC3co8Y_zE8DQToTjBgb3EN5CnRjDuMwcYMO5mBRJ0aclIGn_yV0sv-YMaztGmkc0571lOIru5C1yvwc_qTEI8KhzsDPJsEYoYYPeZKQqU9fd2rmypR5CIFBaf2hg', 'https://lh3.googleusercontent.com/place-photos/AG9NLjCDjKw4l57mTC0tmugGF_hZbf8aG1RKJdVWLyvjsKspqfepfZRCqUw_F53y6PWaAJLMPt8jzuQ_ixe3kjHWYxvS0R8YaMrClvj8btO9njH9kuIEeE5ed-laXJlRx_MsI-05VLafZODviYk7kA=s4800-w800', 2048, 1153, 'Bâng Khuâng Café', 'https://maps.google.com/maps/contrib/114561003296126582059', 0, true
from places where slug = 'bang-khuang-cafe';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJo3EOrkgvdTERugtI46wHkmI/photos/AWCwydjmUKxBTq2HHxP7sTiZ90EYNNU6W19ripxNE4wNENIB3rm0qTJyVv8IBHrl6XUGjWQlTy5z7YcQsH0NRJHp93-QJ1sR3sds-is9U6YS9_OOPCu-2gdrNt4KAjClO6OGhL4pxxktpmW2u7arMJK6eQ4RQeNfaZNmHKSVUNSw5xnSqPEkMkVc1R6SsVQ4yJRYXPMejb24QLb7wuOkb8X6OwPmfpmiPNZc9fM3JhFENnhgIPGQeFF9Dk1g5wvY9Rn7-WfNrdDJzKowrfqokpywrIIQfDSa4uajGIhy-fh_WXG1myxNQ2GRVd-sTK-5vpuMHWsXdHwyITFNBBmOuzgcd2TSFNWnAPNJeubN8xmTFrDuGHSVtBWY-u6Ydk9nKcAuqTIref-iHbzkHX4vGjl_lsX1BJ5j4CJvpGTWiGCyOjTBHPg9', 'https://lh3.googleusercontent.com/place-photos/AG9NLjD3kzlAsK2bVwFvcLpnjBYcT8abIFv39oD1gHAhT48FrsgnCfi6pwyxnnI4CqIY-mm8KSwPsJd7ZQkWVXCXjXClAz0me4Cl6rGGSjVL2jzFjdon9YfHJ52732ki1GmJPdFngNzHxySv2Zq7pqA=s4800-w800', 2048, 1152, 'Felix Süllwold', 'https://maps.google.com/maps/contrib/105489895019978917349', 1, false
from places where slug = 'bang-khuang-cafe';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJo3EOrkgvdTERugtI46wHkmI/photos/AWCwydjDvQTkJ12facoBCkGoyxeQWZryiwycbDZZHkd7e2Hsf2DKyKBQWsmtenxuDDOAy6WCa_fYoEbM7qDuFGYmpU-ts8tUtoXFlKJOa9nG83aLF-af4dG6u51XBVT37ZzDd0-1uSHcvmq7BSX2Kx766zpdq__6Mi0z5_5d_aM_9SyFQFYTe1M8Vsd15xTTny5_2LaUDIQVFzgb-651dBEZkaZBnBpHmvHZGdR4kv-_1FNCJ9AnFl6A8mdZEPGgTNvvzZbzCh3Sy4Wt211qSdgVWWLJrd3bVkcyOMwiyeGWwBPFHFbx_x-mkZepP2KTNl2w-PxzzpERU4lysOcQhB-POZtfBxHtRw48iL8x2G5KpJEaZyI3F2P55zR48PKiWsxShLB0r21_NUoI9VwqSADOn0Y9HovcX4mZrO8TSYgJam93-G9kIFkJJ7EIvJqjLO3_', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDU1D5BV-YF3yBjxJxEWWYI96I9D9UEuf-8cqXFgq3N5lxC3qHk_nCpT76v3sdc0M0T2ClMO_Vsg_B1vJW1Kk9nRqOOJLQ9cWOf-vvwYYcJrrOVKm0wWXhatbL9L4ceLtq7aTnOgyfvNJgUFgb8PHRJUg=s4800-w800', 4032, 3024, 'yoshi harada', 'https://maps.google.com/maps/contrib/111970408196976304964', 2, false
from places where slug = 'bang-khuang-cafe';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('cheo-leo-cafe', 'ChIJh9llDR8vdTERBjmUkPp6GPk', 'Cheo Leo Café', 'Cà phê Cheo Leo', 'food', false, array['cafes','culture']::text[],
  'Bàn Cờ, D3', 'Bàn Cờ, Q3', '109/ 36 Đ. Nguyễn Thiện Thuật, Khu phố 8, Bàn Cờ, Hồ Chí Minh 70000, Vietnam', 10.766997, 106.67985329999999, 4.5, 200,
  'PRICE_LEVEL_INEXPENSIVE', '25k₫', 25000, 45, 60,
  'Saigon''s oldest café (1938) still brews vợt-style in clay pots — go for bạc xỉu and stories from the family that never stopped.', 'Quán cà phê lâu đời nhất Sài Gòn (1938) vẫn pha vợt bằng siêu đất — ghé uống bạc xỉu và nghe chuyện gia đình giữ nghề.', '🫖', '["Monday: 6:00 AM – 6:00 PM","Tuesday: 6:00 AM – 6:00 PM","Wednesday: 6:00 AM – 6:00 PM","Thursday: 6:00 AM – 6:00 PM","Friday: 6:00 AM – 6:00 PM","Saturday: 6:00 AM – 6:00 PM","Sunday: 6:00 AM – 6:00 PM"]'::jsonb, 'https://www.facebook.com/cheoleocafe', '+84 369 626 363', 5, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'cheo-leo-cafe');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJh9llDR8vdTERBjmUkPp6GPk/photos/AWCwydjhl3URDQxO9nc0isCXCUN2ze87bex0WEfwnMdWQ4v3SPiz017CAHE_GdbZhteITKuvJKGiFtAYPQ-D0p74HCLk6mS_Uv82D1yOylno9RUHS2vVbk6riE2FEwHiZdfYWPIzQmIy-p9qOXpHiCJJkMSl2qkViyiFHPuQTJppkqBFUK0uyEqJUjs3mBLlEKBYJAGZkq33K0FYKGBQW-OvU1ETcTDqx4bHViQkRTCaAmTNlPUO8aPcui1zBP7dnF2l881YDFjZZ4X9bn7kU5tP8Dxl3JiP6SW5vMJf8gUiLeTlc1YGdBrulyvOGStmyFolOP8Q9Fd6xuxlcZtyouti6DNdhPY7r5WnBw8HIEtTzoV2hC1TDHzwrcng4YbUlSyeG7L7WTpi9YC8IQney2NEe0oP82gwwJ83QKniNknBHOMQFNIi', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBL_-KZukGVswqqVFmD8W5mBE-mi_ob165-pFxOlgsow8Sv0YIhClk_YHfIKJDKW1SqS5OGs0-w8h_AwEhu41IJRgHdWBc6uje-RROXb1pxj0ZL_xr8qftVPlol2zIFGVF9cVXaua2xCgoSplo=s4800-w800', 4032, 3024, 'CHEO LEO Cafe', 'https://maps.google.com/maps/contrib/107184839502948202751', 0, true
from places where slug = 'cheo-leo-cafe';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJh9llDR8vdTERBjmUkPp6GPk/photos/AWCwydhlS5fzD364OqmNtg7whpAQ_ql3pjnj3tCIHEiPL65esZKoHXQ3XS7DFhwF2aIh3VhYSNVvhkXCVso1rjWc7I4Xlvc0JIBzntOyEq-b0-VSQgaGnZ8uMikhhm6TUu3Q3eUje1zx6QRoKe1TDs0xygSvqnBOYM9_TwxFlF08ztQpPecJMUQqHVhiW3XqcUWYF5TdwAOemf0WMyeoeKF25-dJU9X4dxG-P2Y1-Ef9dlYoOQRidZqGaW_RF9d56bHONvIdkvC00hZkpJ8JT0DrPu76-DV6e8DS_oYCZear2OAG4PoY0gziI0CFus8M8UN-ufuyUaINqiFZ-R_YbLulQZiN8SJUybmz4Sf6syznsh2hF3MMprIKqwrjH-smK1-jTzsAGJVFruiH5xOE1DEhyuevqkZaeVbrTaYuQ89-owpGG1mf', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAgMCX_W5sXLSMbb6c3F2EXAyOh6ewm6UlxxXMfytzoWvmsfVAgJIqwwC1gx_VW6zus37OFWgwM_gYjFzC-2eKonnEM_eNuW1nalr4Bj3BVsB18HvkJz9fsf2TDbAqygGD6o6_7QkhiRbHxKtc=s4800-w250', 250, 250, 'CHEO LEO Cafe', 'https://maps.google.com/maps/contrib/107184839502948202751', 1, false
from places where slug = 'cheo-leo-cafe';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJh9llDR8vdTERBjmUkPp6GPk/photos/AWCwydhnIgroKwWctONOBJtn9OLWv26BLAYvQ1A-kMOIfReuiQPiRBIeFKaL_c-dcuSzATyIAMRV1quaMt9Uu4Ex5spoWRYlTO63NAR77hstnZp7j7YAVa6PJx_ERR1ey65tfZelsNzZL4r_lHx3RqYQZ_SNttz3z35yyl_XVPj1xAD1VBnSfBaeT2Uhl_Dm9Dg2Cl6_nOfFq9bk3jXOfSZDZktTcA4iZn-17czsfQUE2cHttIrZjsPKoz5AUH_6v6dM050WYsTljKBhUhY2tCe9xCylIPp6G_lE54MuUXyrAs5r5EfjZ6KHztKiSbE214lAzQYUO9XbgCmeVb49sRcEnaaA57GsxHynxe991fBQYZRx1Apz1m1IweseqeO9D0MROlyXPJec1y-OZ1ymf2wGJxI4UvdI35IsXGanhWeHbY6vQFK0kYtaUHHnuV3dqCL6', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDUZ4Hz7GiEDrweJhF-dqeT1dU-5RcbvzrmWa59VZ-sGO-Jk9MR9iIoX2QKJIHvM7hRwmwr98mgTcM25TwhC-Tq2KYkjs0VlNqX65tqNeZdXCcOpx9TbQGKgfLK2YfNWYdld3T9SXBzBQ4oPAUnpphXLA=s4800-w800', 4800, 3599, '蕭嘉麟', 'https://maps.google.com/maps/contrib/113497403507409942239', 2, false
from places where slug = 'cheo-leo-cafe';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('oromia-coffee', 'ChIJT9IBetEpdTERv1WHWPOkMLo', 'Oromia Coffee & Lounge', 'Oromia Coffee & Lounge', 'food', false, array['cafes','chill']::text[],
  'Phan Kế Bính, D1', 'Phan Kế Bính, Q1', '85 Phan Kế Bính, Quận 1, Hồ Chí Minh 70000, Vietnam', 10.7906677, 106.69836169999999, 4, 798,
  'PRICE_LEVEL_INEXPENSIVE', '80k₫', 80000, 60, 120,
  'A garden villa café with koi pond and shaded decks — feels like leaving the city without leaving D1.', 'Biệt thự sân vườn với hồ cá koi và hiên râm mát — cảm giác rời khỏi thành phố mà vẫn ở Quận 1.', '🌿', '["Monday: 7:00 AM – 11:00 PM","Tuesday: 7:00 AM – 11:00 PM","Wednesday: 7:00 AM – 11:00 PM","Thursday: 7:00 AM – 11:00 PM","Friday: 7:00 AM – 11:00 PM","Saturday: 7:00 AM – 11:00 PM","Sunday: 7:00 AM – 11:00 PM"]'::jsonb, 'https://www.facebook.com/oromiacafe', null, 2, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'oromia-coffee');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJT9IBetEpdTERv1WHWPOkMLo/photos/AWCwydhAftDHZgfShsNvUfY0CwqhubrOCFXh0d5i8GM4ShXN_PTs-VXbh_0DwXSl0FmbJWbZ8tFQXvE8i8L5pcrlkGIgDgUJaW2N195NNZ0rDBMwWUPzoObczy1DsLak5OvE_Fii5PV-hf_VDJ9lzICJlr-Npq4lLe_MAoKo3SMhtmU_zr6SGy-hGMQcMzwJOibUBe4GRQUrUn62zYg0O9C-XVmXT8nCyooGEKeqxtOOIdJtLqPfn_Kg47aZGH0DOfkE-zoUjARCdttg-5PIW5ovFNw1O9gG2mfpna7GyF9MPcj1y5owaFa1mBsVdn2fs8bmsSeWFt94MVGTNNpcS8YIE-hOqM5Usa7binGDqSZTBYnTX6HKe_CQwuF6EvDtzeGa8_gLt4gW3p0zWCS-BHEmxx1_zTG7ABHnhvsVXlZB_xbUwLYJ', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAGvBdKC5Ng0j8JqsGJSIQDjINxcfeYINmOzsveGlESQEYVN-ZO1adHDr3-rMkM_h82nURsPnCp5wNOWrLQwJsEwtaod-TtrQlgWb5DQGqLclPDEbD24MGsvSkkHq_Kbo60Xr7-CDqF27dcDWg=s4800-w800', 1085, 1356, 'Oromia Coffee & Lounge', 'https://maps.google.com/maps/contrib/111644447834624957230', 0, true
from places where slug = 'oromia-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJT9IBetEpdTERv1WHWPOkMLo/photos/AWCwydjvhIimpz-HryczJjtrRn6cAaX6GGV9Jty4oVP_QIbLRpcyCD-EXP6heNrg6Q70EMBTpYsyHY1V1D1Wnsw7GGMLVBJb3tSBl8tkDctecaL2CmWjvMTOIc2tnRDdiefJXPPzzNN5Db3MR9nq2sXbv5Y3kUNmLMoL5yTpmcZG3QdLpRCdAUClVJ7BH1yH-W4L2GnuUYXWZquLPaZNwzEuTLSx-nlymZQRtJvF_8BNcwrS3aFGAdQQDzoKvAziw0W9yK8IRjMHSdnf_u0QEqAnAx75blV3-aKTLow54-0pJBP3_EUugE7U_yXU2PlK__ITK6gI2qOcwGZwgj00rCrdOhkmC9nEa1REvulfFUBOLwsVuo5Alh3hHLWdFAYxq_54dG6GUgrkWKUFyzGaDDZWS44lgV8z0HxvcQPw4pne3ipftLKj', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDKQi2V6QTeyONAfTTpVN_NF2VTKj1lcw3oBEZsmGDJG2D8En-H0ZNkwsK2LmDcw-0uQ0WuTsGQEJNA50d_9bpRsWk8RBX9ljkzFpRtlMPnV7sdzO-WXbjzcLYPmgsb1g7lFRAuZ2rUJz5jrd0=s4800-w800', 1047, 1355, 'Oromia Coffee & Lounge', 'https://maps.google.com/maps/contrib/111644447834624957230', 1, false
from places where slug = 'oromia-coffee';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJT9IBetEpdTERv1WHWPOkMLo/photos/AWCwydiQJxO0kI2bwNykhiB0cOw7HUUv_LXlXP5oFm3Ndx4DtCeRHM63ZsPqEDhHp8zw7hsCmj2nbCZpHAMCOgWVVv1JvXUdhCXHfdg-t9iJURCyQiLn2mpq5UKVKUkL9ZEW0TZs5WNAMfNCR_D2x93Mu9EIEtJlKfQFfnhFtljIXhEdSav62sLnlKduGyKSgJH0Oy7XSypJnKrspXL4buo9tkzR8nj0S2WIwXP7d8305Y3iLscSkPf2uKaqfzP-Sjhb1i8Me7kPinPpwHLRMj32P-hHn4PaAKz3W68RbZN4vGdw_R0N9YLudqZY_4yn7Og5U3IR2iKrC5ZUa-kwJg5EafRoQxu2t13SGozKHFMholfHp2m-UcYJ3aQHfXjM2f31hPzpXVEhe6NtOM6F7J5vWePprYRkcsA2H1TMXQCOMVRmYg36spoaDiT65EB6IuCI', 'https://lh3.googleusercontent.com/place-photos/AG9NLjCwsGLv6Tlrh-HpEQI8lZQ6FfGDjpRo97Ng_saZh_pz8lDTn22ozf7mOsrew692AJseSxeun0OhUieG18NMbJh6gGTs_s8FLK8Zg0kUK6rd2m3b-3T-lzCPjDTKv7ZPCpDGw92_IBsIpNDn6j2ud2w2Og=s4800-w800', 800, 600, 'Rohan Kumar', 'https://maps.google.com/maps/contrib/100712841069296848065', 2, false
from places where slug = 'oromia-coffee';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('lusine-le-loi', 'ChIJF0H8qzgvdTERzGHqj3yiv4I', 'L''Usine Lê Lợi', 'L''Usine Lê Lợi', 'food', false, array['cafes','shopping']::text[],
  'Lê Lợi, D1', 'Lê Lợi, Q1', '34 Lê Lợi, Sài Gòn, Hồ Chí Minh 700000, Vietnam', 10.7743611, 106.70055070000001, 4.4, 1267,
  'PRICE_LEVEL_MODERATE', '150k₫', 150000, 60, 90,
  'Café, brunch and concept store in one colonial-era space — browse local designers while you wait for the eggs benedict.', 'Café, brunch và concept store trong một không gian thời thuộc địa — dạo xem đồ local designer trong lúc chờ món.', '🥐', null, 'http://lusinespace.com/', '+84 28 3636 6512', 2, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'lusine-le-loi');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJF0H8qzgvdTERzGHqj3yiv4I/photos/AWCwydgr7NfbFoct4FHYxJptYnvnygWcZQlFXVPIrWwpLQRx_7-KSh-jDO_X15HLp1iiDWM25NqUvwD0xgRL8pecHUziCyWeTAJSDTFq_9UuVn-h-mbI_WBS64bVUJJofriT-cQbiVihktnzdmRJdtshz533jhQNQogfgi7ZiTDxfR-VvzQbFbL_ltIGQchEsPwrVOCelObsZax8iX3FNgWoVtlATUyrjf-jG9JuF8gG2up1yhwpQtoHZ3AVt69V8RYq7ePrPDjahy8Q1lv-jTkHYUImP0XSs1M-dtDHbCbXLKLKIk7QAfIQRgbWB5hLJg-Wnzul_B6sfassnmC-H3DCRMdJfl-ozfEhP6dCg-X8n1pkL1JB1B_zwx-JBHFcgwylaCdfg6610Xfbsy7siPQmrK6U3ZTy5EggyHh9KDDT15b_w_Em', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAjLJCo7qN0qgoSINkFgn1xkDyEQQHwMZzUIim1LBxsZQEybB8sR9-ayLwsqz37lB78mSL5yxvIprCjWF1WG82uQS4U7BiVCWsvYmoB_o-0wppDaRxE_zqz7j1teEWhz5vjUG7pKUttXH2uJ8Q=s4800-w800', 4800, 3200, 'L’Usine Lê Lợi', 'https://maps.google.com/maps/contrib/114772649037932743948', 0, true
from places where slug = 'lusine-le-loi';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJF0H8qzgvdTERzGHqj3yiv4I/photos/AWCwydgUeWsidOUXXFeGzRI03G92vX2bo7cfmsK-JlZzhHv_6m2137YnZWOeI3ilzUnO_L9_dChGPZigcNJf8-SSWsOEHC8TNrKFSmWVg322RAtAAWOmxW_22sIBeNy2hSHV93b0PaM4fvWLwYljCg5yC3Uk7DqoyBLsKPT7vJgBqwbc2urOxGs5DWAk7qivPemct7kn4VgpEUOMzqOHe6tWFpLs0zGZ-a6arQL_jh5TuAScnZbFOqtzb-HPXt5AgPxSw6UVQ335kcJT3yxRIc-ddAb8-qqDf_ZwTb2VD4NuO1exe8fhIOdaYJDJOs5OJdZg8569hnR2AokHhw1_gJIMsiZ5G6sD4D0mSDoYtiZAEM46voAkVSGWcn0AOhw6JiwhCqNLwTWdW7wLscGOdvdkK7YTbgOLkxctRvF1glEGCytx_Nf9', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBxwOUabPTJxzA7zZOkSrPh9pQNfo9r-7a_k845pz1NqUlzCqPvwA2194RhEvkiOP-FijEaEP8YfCGtEm4g9S0e_nPAR4MHK5rwMMHBRKqlTtNlfWTsEWkYMwUB3YcSQ1z_K-qeSXvz6CGL5PE=s4800-w800', 3549, 4800, 'L’Usine Lê Lợi', 'https://maps.google.com/maps/contrib/114772649037932743948', 1, false
from places where slug = 'lusine-le-loi';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJF0H8qzgvdTERzGHqj3yiv4I/photos/AWCwydjtifhuxTngNxuMHK0Mg9KaqqHNJNiQ5LcP2a-TySTFk8YfEMpl-XXNdQ6oAZSXT1ZLcWeOvTAp87NARtoGTPYPkr9jpSUxZ9QSjuo4g1Ve1kTXw4CGXBtkqQMRDABWQH1GOPuB641rVSvVrjREn8ENhEYrxOaRHg-57gxjsMnPb1umya3jPUmadxBuNwU4fMX-QdoqXELVb_pZEkSyeVMD4HUIGF-oZtpzBdEAkFQLQdTkfNC4AjGbBM7orF--tddzDL6yY-tsGj9f-bm4ImDZ4wMo0GVMrTK2H79aDM7RCMce9KY3vCeYyG5oVO1pXuWBaZSg2chPAx78CExwOqbIx-nYOQKtf7cWu9O_zGZKsuJ4PiuBHZa9jkZgTleqGtKibsYLsyhhjmZmSPxTI8EmlrY2dlMZfQg-7woYJsDvrQ', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBReNTknYwncAzTo_Ov3Nv6G2JPTGDqggz5HOa_U-08x4ty-sHu9wPubTstzsMCrxGR2T9MN3-22rF0x8REw3CNnuo0MOm-JSGrN5e9kzqwTBTdGo1e5xjrq--GRJcdcMsMUdj2MpM_k3B2kw=s4800-w800', 3024, 4032, 'Isabelle G', 'https://maps.google.com/maps/contrib/113373817074082737499', 2, false
from places where slug = 'lusine-le-loi';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('ben-thanh-street-food', 'ChIJq1TFWgAvdTER5mGHvfSacSs', 'Bến Thành street food', 'Ẩm thực Bến Thành', 'food', true, array['food_tour']::text[],
  'District 1', 'Quận 1', '32b Thủ Khoa Huân, Bến Thành, Hồ Chí Minh 700000, Vietnam', 10.7737417, 106.69729439999999, 4.3, 1500,
  null, '140k₫', 140000, 60, 120,
  'Classic market stalls — bánh xèo, grilled skewers, chè. Easy for groups: everyone picks their own.', 'Sạp chợ kinh điển — bánh xèo, đồ nướng, chè. Hợp đi nhóm: ai thích gì tự chọn.', '🍜', null, null, null, 5, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'ben-thanh-street-food');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJq1TFWgAvdTER5mGHvfSacSs/photos/AWCwydhfgvAgQZyciwOM7yumJCMgWZdntFDwiEcalMOrd59Jb9rKDckUSEmGyYttFF8QyPjSQVcUU40W6YNBdVV8i3Db3JSPziqXZaXwYFx4J9rtaV_ASJwsx3BPbHEhtTJZXpvoSzHqEdJoA95Nx9KGLHPa_aPBCsZ4IfmsSWy0VuoIF_JLeFKYtGiYkNVLfp95p_xaj7UUXHjGY5Isbu3Ohl4tm-tJazNsn8UNpJZ5nvufmCGT7ySdbSkvbXZt5O-dqaiKiCh8GDxS48KWuNdycFHmPYKqCnQkZleXwi-1JJrQ9Zy-pswI5U7Irbxq2H1pHfuCpgdYt6900qtauOg5CdgYGXyBqHb9JCox_VlURN13IyfDt_YuWAozmCz9y667qy8CbiCs_fqQCj-G1_Nikxr2UshbMJlYFD7bV_L3dh61CA', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBsfiITgzB4SvmYqiXtnqrKIQV2KAQIpLJWY-vuWbVXhFBwKfxP66rqVBI15tjUN4TDfvi_j3BIhSW2hGOBWnE_JlIrtXj6oY8-DW5R7d5sHOyM4cQi-imvT4EJ_S7Bblg4_VUj2lL-8KviEg=s4800-w800', 3952, 2290, 'Bilal Rifat', 'https://maps.google.com/maps/contrib/103621954677239724748', 0, true
from places where slug = 'ben-thanh-street-food';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('secret-garden', 'ChIJQxLkCTgvdTERwY7eaX3aK3g', 'Secret Garden', 'Secret Garden', 'food', false, array['food_tour','chill']::text[],
  'Pasteur, D1', 'Pasteur, Q1', '158 Pasteur, Sài Gòn, Hồ Chí Minh 70000, Vietnam', 10.7770824, 106.69975439999999, 4.1, 4779,
  'PRICE_LEVEL_MODERATE', '150k₫', 150000, 90, 120,
  'Rooftop home-style Vietnamese food under lanterns — book a long table for the whole crew.', 'Cơm nhà Việt trên sân thượng dưới ánh đèn lồng — đặt bàn dài cho cả nhóm.', '🍲', '["Monday: 11:00 AM – 10:00 PM","Tuesday: 11:00 AM – 10:00 PM","Wednesday: 11:00 AM – 10:00 PM","Thursday: 11:00 AM – 10:00 PM","Friday: 11:00 AM – 10:00 PM","Saturday: 11:00 AM – 10:00 PM","Sunday: 11:00 AM – 10:00 PM"]'::jsonb, 'https://www.facebook.com/secretgarden158pasteur/', '+84 909 904 621', 2, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'secret-garden');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJQxLkCTgvdTERwY7eaX3aK3g/photos/AWCwydjJ_L4DkamdUEnboRyA7W7TDUpW2OxDa9aAuMKjTXQkOQW8cwXMfq-S--uSLZms-HEg3Z87lqIGRUNiCgKbFuQYg0veaoBQuisAnvXTB0SzxsbcWodby_kkYVplb6DZlNf625qKgF0iQl8oMKNqCsZsvv1OdJ1XVgCIuZb0TYBfpMEcgFeHy_ZKuzqoiC20z5QZy-SsAZw9BaPWYhbk68vPVdi34imetyLd-KNduPTpeaioO0btXz6OusDecKhWE1FnnS-8Ldrhf-1GqT9ZntpEoXsTYyiWJpzsherA_IOSDi7EY0MlzX8nRpdT-ImQB0173DAqNN_XFvRWvt1xO_H6_U570EDbH6lRT1FNRx6KvZJq2JxU1YvbHCah7TUCOE_q_NVOjr_2JkzlCz0NLptcyFfuFuuq9uHipixPWZ1tuUQYmvA39qum_--mew', 'https://lh3.googleusercontent.com/place-photos/AG9NLjA1MqIQskZ69N3X90XMBWpMDCmL_3gL80e7i2CB53VMvei7FecXBfM8g4UwishnFM8PewbDlgo93LsdtNYMyRccVIczWrKeOL02iBdrnc2EiZLYHA99NbX23_2UyJ9RndxI2zmR1wBbrainaKzfze7L=s4800-w800', 4032, 3024, 'Tommy Ny', 'https://maps.google.com/maps/contrib/114261712974779335726', 0, true
from places where slug = 'secret-garden';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJQxLkCTgvdTERwY7eaX3aK3g/photos/AWCwydh2ynUb3aP7tmbbk2X8Rrvz4vTjUmzZkbxrVfBLSHijwsbVArR924HZqUQYEGK36u8_cGEG2TRGNME-eW1tBj8OIhoPCvDIFh_7uWdz5Tn4NNOTvHACRwfjP9zWy-UAa0ps9ugmbsiyfFrJZz9iGvQD7i2YE7JYFaBsoXxpjzmIFHNMuuh-KVhJdHs3NDPz_KIzqiHWoQvk8rD3oUcOAEayTqEC8epttDgFsd4FZ9kN3s4hUp-77O4GTyxlTtgAKtBHvNVNXfvJM0t9lA8KHNDt4oMTtXrG7wnxfVkaB9bfox6guHKjJcpa-v69gZyksHvyu8qZsN_ExMRu3aUziiN1RLRISqhieXaMFOtXYcDm4EEFuluJXRq-BxSUqoXIyJqeG_KVkPkng3rEzs-9hwU6sy2mRWd6ikA4vYotNPnEUg', 'https://lh3.googleusercontent.com/place-photos/AG9NLjCEox7WagxCFivyRIMXim2skO103m75ZZ_4v9A-ELDUHz2UOkyUlTXl67A0HgVMl_NfnwdQwCejPvKUwNCXhoMIwESy6wDFX_CBx0Fig8ag8bUlyeHNKydvYMXRPagIFaN7GD0oeezsFKufjQ=s4800-w800', 1440, 1116, 'Secret Garden Restaurant', 'https://maps.google.com/maps/contrib/108517894477651113279', 1, false
from places where slug = 'secret-garden';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJQxLkCTgvdTERwY7eaX3aK3g/photos/AWCwydhZS4Hi1H36Rdg0AjHBUwQLk1M3RPKcaPWnprzQWP_0S7wLBE2AxIbMyX_10w8usP5QTJLQLWA8UX9jshrfly0fvMKInjMhIYVPkZ7X2LzMkdwZMTL3MKHhRIjo0s5FtnZl4qZXkf2QGglwW_WbHG-RDc2bfQ4ZGQLsc5Zl6PeP26s7mhEKqgvijxpK2_UZRULKW5Bvb7C6R4Nnfqtveqv_B9pce00D6cCQZ6WqWkiq2VjsJiTFGuIy7Rq2TTvOPj7VXsYbhW7r95kFSf8-Qi2IjfJ0ojXGP0cfSBEVE9FBAdYzr0PNEy3Wq8MD0e0paFJY7q1iDAY_2cgSeZCXPOI2KqVKNNgZuJNjgSm-KL_LdiQ2ls-ESJ77hZfVRCmOLZg4wUMJLBC5ePa9afUd0GTuctNEKLRKzlOWR6qOK6F3mzJrFgOL21t_HGgusXmc', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBtQEqpyC0QjVAyPaFWc5griieSljDJ4VdyXZgEIsArjuwLU0uUNOqlKzFzYUMDu69kvcYQqgZQHhI-ThoOph-Dks21Kvm7XeyxbDqKYzp3lu2BU-HNNan63L8l2G1aU-Giq0hRFPnVuIKuCQzg2oXNyA=s4800-w800', 2252, 2320, 'Anh Nguyen', 'https://maps.google.com/maps/contrib/107910297214128661084', 2, false
from places where slug = 'secret-garden';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('banh-mi-huynh-hoa', 'ChIJ9bBIK5ovdTERXOUNNEW8YGo', 'Bánh mì Huỳnh Hoa', 'Bánh mì Huỳnh Hoa', 'food', true, array['food_tour']::text[],
  'Lê Thị Riêng, D1', 'Lê Thị Riêng, Q1', '26 Lê Thị Riêng, Bến Thành, Hồ Chí Minh, Vietnam', 10.771522599999999, 106.6923968, 4.1, 7530,
  'PRICE_LEVEL_INEXPENSIVE', '68k₫', 68000, 15, 30,
  'The most famous bánh mì in the city, stacked absurdly with cold cuts and pâté — expect a line, it moves fast.', 'Ổ bánh mì nổi tiếng nhất thành phố, nhân thịt nguội và pâté đầy ú ụ — xếp hàng hơi đông nhưng rất nhanh.', '🥖', '["Monday: 6:00 AM – 10:00 PM","Tuesday: 6:00 AM – 10:00 PM","Wednesday: 6:00 AM – 10:00 PM","Thursday: 6:00 AM – 10:00 PM","Friday: 6:00 AM – 10:00 PM","Saturday: 6:00 AM – 10:00 PM","Sunday: 6:00 AM – 10:00 PM"]'::jsonb, 'https://banhmihuynhhoa.vn/', '+84 338 044 646', 6, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'banh-mi-huynh-hoa');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJ9bBIK5ovdTERXOUNNEW8YGo/photos/AWCwydhKPvPDO1e0A1KFc4jl-sS-zBrNeyxO25UA1IGmDzD0b2NkH1DDmGlwTP_9DAIc3YcBqOQsELEkXo3LUvyLPp5pGbi8nK75XSzHQdcgssSL7fRcchYDaSucDKRSzfOrcGGDDSngFUqC2o5CQTRWJS7mKnKb_-cxlIK0VleOPVR0hG-P55ezT4wu1hHxfKRytDSn7y4-hhW7ELUqOrYxujOxekeym-XZsPjhYNwBcnk3Zsr3P163YyVHUn65q-HHYhlZqUoGSXR3HnKv06S3j2coogsOgYgPJRyTVXDsrN1s0NH75g3RmEslRPivL-prxzfHcEI-x54NxlOtQ1wqNbzmDrZRrQAqduw4WrNE-4I6zhwk4LrYUXl1kItN6yMnaNH-nzePfnJQuo7sYxmfaj0QiOxb9o4hYXjgbOYzIGYX4ncacIHxPTw_pYYkhVjD', 'https://lh3.googleusercontent.com/place-photos/AG9NLjC3nfKc7w05Tv07agItt7eKHSaK9Jne82S9LrBwTiRZQfF4YtCzFAGMsFsHDj62oUdWkzMibwTn3UgaNCR2zrxuYofQXkwKkpmR_zOPtQLCLQqqdKkBtAy1TxAKpYGamTnDmJ4IMw0GZk0ytnWzREfYPw=s4800-w800', 3600, 4800, 'Zhi Qin Ooi', 'https://maps.google.com/maps/contrib/112083975906563403770', 0, true
from places where slug = 'banh-mi-huynh-hoa';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJ9bBIK5ovdTERXOUNNEW8YGo/photos/AWCwydg6m06__YrKzdKx9KGoyAHEji5F1juz4LTzADOE2ImAsQvne09c9ZFHOTTCPjTccQACicQbj6B39H5NDtxUTcH84cNeF_DLB2W3u0O4EVTLBCSZSgBUzoJKG66I-CZGOLN3-nM0ZlYGN2i64dtZe6zUBCjeNnjb3ytQqCDLfbe97T9zs46whyPht0iO1yLCBp3Eq69H6nj9L3ybOU895bTN8rhNpA9LGmuyGQxE3P3DVrczgl1OhaJu-V_2sQ4YW14ZOIbVjDe3JRYULcx-RfwI9kOtPwdvstzADLqRxvtILAwdhPoaBG3rkebFjNvHvraPyafOa4lxcXJAI2OPdj_WpdyHjk1P10MyQUuc8RSpVXF4e_9zE22C7JnUF2LIRK9s6jNL_xGDDCmTSxOQgRMzZyXxfOdTkjmwNjfFsSGvQqhtzU01d0jw1-01o62S', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBW631wzyjXx44oyi0UKBZs2hb-eOGRMsRE57EipB998chJc2VF-kFoP3_ZuZIRypL5mOlxYDAUM9uwUmQ49FCbTutq6zmjyH_qC1-zJtvpvokROidSOQwdVJOs6VEvY9wVUe6yeRuJ19-o8yZ8ZuVnjg=s4800-w800', 4032, 3024, '葉家豪', 'https://maps.google.com/maps/contrib/105546766132576466480', 1, false
from places where slug = 'banh-mi-huynh-hoa';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJ9bBIK5ovdTERXOUNNEW8YGo/photos/AWCwydhoQWinRF2-6stWOPcPdXBn9husMBShCALslKgp5T8MQOBrtjYE9-2DU4QFaX_fZO_8NqQPZKAR0GdpIcyUWF22obOZXICyyMN0gi6cZp1tVjaKb3nIIO79ohFiwnkWJU_QZoYjHCOwhX77irphRFWR1GPcncCnURu0EaOQuj8vvmWf6XApZg-iYXVU7o0bEnh_caHBhdrFMzhcp-f3vjwnM91bjSCgpm8ZRfFsW0zuFa5biyo9cWvv-Sd9xxyKaBXaMn5ourknYeznXvdCMzi0bS7FzcYBMLIBvxXy-B3OA3p8pgLK6Rn5fHQ6yXX0zMrhTz39iZHWmeVaaPabA0WDPKjzsE15hsl59GqdPGZ1VjBLSejAv8SW5He6zNc5yhf9yL1ilYGaAux07d89Y_ft10H0z5VUgqsX_iFOFOKp6W68KLOs1msZg3WVtA', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAe8ParxjGxybzi2T3fM_o7VXZ0Xv43NRQe70dUYR1eCLpiXvtmWTqWXfI9Ad4fO5pQj6A24PRa-E-m_r-BC6ZiPCya054FKVAr1L2wu4XsSGbA_GZ33HnrJlzOk6uq2LYPVYk4-T_aOYe3vNq6pKmz=s4800-w650', 650, 485, 'ngọc Nhi đang buồn', 'https://maps.google.com/maps/contrib/117343170390869295506', 2, false
from places where slug = 'banh-mi-huynh-hoa';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('pho-le', 'ChIJg-GCAP0udTERBzmwi8B6NV4', 'Phở Lệ', 'Phở Lệ', 'food', false, array['food_tour']::text[],
  'Nguyễn Trãi, D5', 'Nguyễn Trãi, Q5', '413 - 415 Nguyễn Trãi, An Đông, Hồ Chí Minh, Vietnam', 10.755295900000002, 106.67351959999999, 4.2, 6049,
  'PRICE_LEVEL_MODERATE', '90k₫', 90000, 30, 60,
  'Chợ Lớn''s beloved southern-style phở since 1970 — rich broth, tender brisket, open till late for the post-pagoda stop.', 'Phở kiểu Nam trứ danh Chợ Lớn từ 1970 — nước dùng đậm, nạm mềm, mở khuya tiện ghé sau khi viếng chùa.', '🍜', '["Monday: 6:00 AM – 12:00 AM","Tuesday: 6:00 AM – 12:00 AM","Wednesday: 6:00 AM – 12:00 AM","Thursday: 6:00 AM – 12:00 AM","Friday: 6:00 AM – 12:00 AM","Saturday: 6:00 AM – 12:00 AM","Sunday: 6:00 AM – 12:00 AM"]'::jsonb, 'http://www.phole.vn/', '+84 28 3923 4008', 4, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'pho-le');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJg-GCAP0udTERBzmwi8B6NV4/photos/AWCwydhs28dVUz-bS0lenA4oYnRicBjc70q-7eYqJ0P19B5uyE_ZZEW6NvG2IUEuSLs85bI5t4Y0Iv3tBMgF4NtjujWh29nB5OjfrlMG84UZGUq2ERoaffyeb1Nc3BiAdJNbAxQicBcgTELGX_5hH0NWWUVuq-jFtzkC9CffSKuuPi8mgQjTDHtI5un4Fas50bA17EJHsmqlUOZ33HQ-nQIZke6wcTEqdsBDvG720OxCxHcb-F4zgWPQ_OeY9xBhcH2o2a4qeQsG_FnubbY0D9iduAsvadA3Qwy-BMhuq0urSRg-lL-bhWd-hDtn-vb0-DcCMmeRMaurcycSYY2aAh0GoQZ_VXmfK7blNqKg_Q2t9pcbMUOStXfaeozZWISLYS3vbQ73gN7atZL_oT7dw6B-rWTEbrFHQPUAz5b_iuzW5qHx6w', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDJFOHA7gSprsnIZVPBo37YkSSL1MNpspPkcqP_e7U4Rx3VaLM8G97YCP0L1xzDcXIePTj3_o4y9Rg2Vu1B7Y5PPnrw_qdxzwAq7c7BtTpOUfSRgN8QCxVEdA6mSXbkpjec1uyULmRJj7ZTuQ=s4800-w370', 370, 370, 'Phở Lệ', 'https://maps.google.com/maps/contrib/116533816795176386646', 0, true
from places where slug = 'pho-le';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJg-GCAP0udTERBzmwi8B6NV4/photos/AWCwydibLhxG9IkkBYLOeRZfXmTeKd4El2jo5ao_ojPbGzLMeMQGTEk1RUvJnqx7HOmbeH3zbw4_sZEJXLr7tHSLqEgcWqPDIBNLYJWCqOHMkEDCpwcAwfGwBtasESJ4w6Qo-3OFdOpjA_eChyVWIh5WmAzOQyFdSkTcdxhzcd7m1DvtvR6Ool7XZSxuWo6AI45asCAZOXoIfCqdfJyV00YcOj_ImAzrsC3YmoDuvpmgllotUW5FXhBGWGiKXzG80ROV_NBJANByPgtumkB_-uV8UA0PNqa-Xe1ticKyxy7IkWJ9EhPLyrTsIRv_56IARhjfPany2-RbZtcfvhoKCo1doEgmuGefdSlOVBtFwFithazmB_DveQ5dMwBCv5tzxh6VbObpN3a45NRNbNsYLmaPrvQ7qkbAc_5npRi2D-RVaq4I7g', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAO5rO5vsZIVAeD108bd1J6YB0zXdOrPUKMR7b1pcfrVNlgTHsG48YlEoEnctUUB0eo29AuNBYjfubpwarC4l6m0YneS-Iu3tFhp6hmqowFsvajbRddGENmNpeCF2ALSKCn75TL5F7-Y4o1lw=s4800-w800', 1500, 1500, 'Phở Lệ', 'https://maps.google.com/maps/contrib/116533816795176386646', 1, false
from places where slug = 'pho-le';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJg-GCAP0udTERBzmwi8B6NV4/photos/AWCwydhb0kbCQSLH7c9dQzGn9CGwm4h3z0RMZT28S7hrhRGB8hvyzYSbM1FRtj7tQjNyqAfQaXNTmFjwosPiwGFMLE9jcxZ4znhz2eCamfsPFQyragACu4jwV-P3SjY7s34Mr2vR2QFGocYSIhTqQEWxTX_MGr2o7LyVvucFld89KVPJn2X4iB9lg-SbGPY_s7V0hPoIDqgUX1LnFRtWrvkCsoCj5_CMqdQeiMb9Zz4hSXc284D1J6bB8iFDEAMFU9A6RL5glDBHdBiBOE9ghCuWI-56yNSO8Ji7wL1QrbQ9OmFjr2vZagNn1OYZY_UJp8zUVdBgizQVc8rkvckSGMgwUeuhrzKz4U-I84fXJmiYJL-pUquIKqMN4Rn3r74vhXMEX-WJ-ul1ne-l_KnpqnDBnMoiDEXek7hm_tEYiQA_I5ZpPUat12UtZQPMZu4mQ7Ho', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDP0mddoGh-fIEmVm6vtZWQwKRIL7d5HZbgY3eJEGojOOPwS5Ywr-QzkD5vnsp4FdYRU1tI86cg2aoQA2N8K0r2H5OeQlMHgPYcZHtWT6biI4bNIKbIOzZqTs4sv7H4N4qxiW_vucH_pR8A4d4V63N1FQ=s4800-w800', 4000, 1848, 'Pert MONEX', 'https://maps.google.com/maps/contrib/100542560408947054153', 2, false
from places where slug = 'pho-le';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('com-tam-ba-ghien', 'ChIJVdCmZwApdTERst5D1YIjVbQ', 'Cơm tấm Ba Ghiền', 'Cơm tấm Ba Ghiền', 'food', false, array['food_tour']::text[],
  'Đặng Văn Ngữ, Phú Nhuận', 'Đặng Văn Ngữ, Phú Nhuận', '84 Đ. Đặng Văn Ngữ, Phú Nhuận, Hồ Chí Minh, Vietnam', 10.794442, 106.66936, 4.2, 3606,
  null, '70k₫', 70000, 30, 45,
  'Michelin-listed broken rice with a legendary grilled pork chop the size of your face — come hungry.', 'Cơm tấm được Michelin vinh danh với miếng sườn nướng to bản huyền thoại — nhớ để bụng thật đói.', '🍚', '["Monday: 7:00 AM – 8:30 PM","Tuesday: 7:00 AM – 8:30 PM","Wednesday: 7:00 AM – 8:30 PM","Thursday: 7:00 AM – 8:30 PM","Friday: 7:00 AM – 8:30 PM","Saturday: 7:00 AM – 8:30 PM","Sunday: 7:00 AM – 8:30 PM"]'::jsonb, null, '+84 28 3846 1073', 5, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'com-tam-ba-ghien');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJVdCmZwApdTERst5D1YIjVbQ/photos/AWCwydhCvnhJHw9Lzaz0YpzK1AXolFrYti_4Z3aG3myC0p5FSrdWzaE1K_Ls_FEfSP0zfnTDYkjjI30qmV7fIq4d1uQzTAOCkObEpVC8eNmabsnAYuyLWGVKlRiPX5JxiQgGtiaYmYcVdlzn4ZiSUUSePS1yRsh8swKdNU8Vhay51Y7lAFXo_ofk_AOHDaYOGZ3GjOWl_Nvw5vgMjNo0kxbIkwL6nGlpbonZreD66GEB5kzpKy9qGgvrYq5_8BDnI2hA3h9hGnc9zj8FrtsSnRnMUsWD2o4CCnpdyzZlLhJigrEUKa0iHlshM7w7qItnlg44NwPZ3CYzNR25DJo8nVicmFFfH-hN1LRPNpWRZYE-DOkIBr4oR_GYvkYNzBCgYOf7J_1d8_1QffEVI5WKmnNdAYXrOu7pjmiJ4Tm2M6pO5HQLFll8', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDTvf2HWPXqt1LJW9949fSQ0sgde80G7cvfj8mXbk3ah1ix0t77j_ka-5q0q-zQGgfnrslkTIqteoXKL4PZyQ3LwhoYQV6NCJND0IgZhM2Sm1Du1E8QXoy3exdz3fnQQO7n9y5st4ikOhQ1bP8=s4800-w800', 2048, 1153, 'Viettel Store', 'https://maps.google.com/maps/contrib/102587055378129974576', 0, true
from places where slug = 'com-tam-ba-ghien';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJVdCmZwApdTERst5D1YIjVbQ/photos/AWCwydgqvAGZBdLiTHopZJRuBzeZ4jCPC0P1fdo4NSEvgLP8S4nweMDpP1lEcGEtRwZkT8u_GRRs0QMO94ScG-pN0yStqpctsQD3OTWewaCjBZZrjiWZGTSTtDNKP30_Fs7iwgARZZnZMA3Tg8bjLtIngrU7B2JU_8U9uRb0DO1DO3x-xeNBk1rzq2Ku78nZfzIBSc5tT_glgIC-dypBXaBP4IDh03rhEXmmhvUt9Xz7QlXXu72Qt1rOwCQq7ZBfvVqtluEkCYAaD_kgWL34wQDJBdmsDU-3dyK1M8aZrFAJE5ZzYqWQYJSYxDrHcUHrHXEdjHONLcYa9QWVJ7jIvcfrRUTB2NRe2jcSUZnnThy2jr9cAAsIBWcwoRoUFTORJyIpsdWlttgjhohNF2A4Mj3m1RTNrntNyEA_PosWXbIiTKIRBGMD_oUpurLhwinLmQ', 'https://lh3.googleusercontent.com/place-photos/AG9NLjCpsBsMxAfTRJJ0jVTDr9_Y40pK4w_-JCAxXpaNxElDstNIrgoJ8XJaY27FOdJWjil_m2yD66Z2dT6xRYzzw839V3tYiF93aRvCvxFXHYWSJX0Ep6PZ5KqYTCa8UplX9Ad3nByv6vSwuT97E5Bvl8OM=s4800-w800', 4032, 3024, 'Bernard Huen', 'https://maps.google.com/maps/contrib/105356211593860927587', 1, false
from places where slug = 'com-tam-ba-ghien';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJVdCmZwApdTERst5D1YIjVbQ/photos/AWCwydgfvW8xyJzxodB84yA1hliHBi4BuK0yITubdwXqa7lfJz1pVGIQIHH8dErW3jBOPYfahhj7MA4X1Vw3MRdw7lCOhlFlL1c4A8-UOuPIt6emVEMnMYZvBGY-7AEE8q8tXcz9sFVTOue163WbghhCpSVldRDgpKZubE_bu5xHkausEXRxWXoOOE0FN8gmltiSM-Anv3W4ITPfPndgfhVGXZYxfSJbeKn0zLvvb3x_3MNcd1B_BacWavNvjlKRYeA7qf4z5cEaoEA5og7IecCxAxBGkkdbbxqw0hsdsXsJn2v8ErmH6njz_6bHEdKPsQdqL_H4UkT5hiBhbfAhZi_DEqOB5zl-7HvEGGhjAlB22IT7IxGxvbpiyRTNTBHiCVYdRYfCO6u6w-_MPknocWBDV43ug0B82L6ktzB1-fqs4Q2xUEE-Z9jowrIHyVpGy55P', 'https://lh3.googleusercontent.com/place-photos/AG9NLjB-1FtkxU-N15UP4tnv1oQHInO1u4OHAEPkNHB0oTM0OmnQd3E9qMwi6_fHFAXMMMr_l5487TRXvZVbxRhvn4TE1WCneD7yKH3H9yeFQN-JHRSJuSHWQ_jCYNkBXldtdIdnn47cMUEZpHk3uRyThW517Q=s4800-w800', 3600, 4800, 'Hồng Hoàng', 'https://maps.google.com/maps/contrib/114211119983595167675', 2, false
from places where slug = 'com-tam-ba-ghien';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('banh-xeo-46a', 'ChIJOwpR9U0vdTER7VWboFERAEk', 'Bánh xèo 46A', 'Bánh xèo 46A', 'food', false, array['food_tour']::text[],
  'Đinh Công Tráng, D1', 'Đinh Công Tráng, Q1', '46A Đinh Công Tráng, Tân Định, Hồ Chí Minh, Vietnam', 10.7895674, 106.6913428, 3.8, 1938,
  'PRICE_LEVEL_MODERATE', '100k₫', 100000, 45, 60,
  'Crackling rice-flour crêpes fried in well-worn pans since 1945 — wrap in mustard leaves, dip, repeat.', 'Bánh xèo giòn rụm đổ bằng chảo gang lâu năm từ 1945 — cuốn lá cải, chấm mắm, và cứ thế lặp lại.', '🥞', '["Monday: 10:00 AM – 1:50 PM, 4:00 – 8:50 PM","Tuesday: 10:00 AM – 1:50 PM, 4:00 – 8:50 PM","Wednesday: 10:00 AM – 1:50 PM, 4:00 – 8:50 PM","Thursday: 10:00 AM – 1:50 PM, 4:00 – 8:50 PM","Friday: 10:00 AM – 1:50 PM, 4:00 – 8:50 PM","Saturday: 10:00 AM – 1:50 PM, 4:00 – 8:50 PM","Sunday: 10:00 AM – 1:50 PM, 4:00 – 8:50 PM"]'::jsonb, null, '+84 28 3824 1110', 3, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'banh-xeo-46a');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJOwpR9U0vdTER7VWboFERAEk/photos/AWCwydiWC9cRHzPz7yPtTcJc7QchR0YtTBLlzHzY3QRfLn0E4OsoU6hdeCM8rw6h1V1JgeoYPMRL5FPKLDBn__YUvzZtMkz-g0iT5QEGQGGOxxntSkbkcc323GlA0g4sumXmZeJA2rw1yMQNPO8y6mvMmEPTNEsNYVCjRXtXM9P0-sarPXsfrt0cSd6ReTayXb_u6Jhxk16M6wNz006gTRBTwdCZz_x9iqPNHsk6zMAZe81yMi24eOHL_LMYaTE1PoKKOqnJyM6pOblF865OthcN6KllV8cVZUa17snwwof4CzMUSh8WLBnF39w3XiCZ16cZIQkakqF4wl16RDixcB7Lv--EP4GpaQeSh3GAyzgbcEfn4idOv0QRgHvYXzr1rjmrVHzoJKbZFrgp7zUA3w1APDbevbAlCzuvLjouhCWxuLjq9f3LM_lkWuAas7wGPo2w', 'https://lh3.googleusercontent.com/place-photos/AG9NLjBLDzRgoIB7z1y21g-dk9Hmam4hRyIosJUp669WAY1IRQDjyXRgrhC9IaGzsUnihP8sC2VuSSxjR1sIYTsfmIVvuxeMtuG6c7IMqY2n63-U4RWhyGfWLdnhHzUc4N4MWkH48gk1R4j9gLWaHyqILdu87w=s4800-w800', 4800, 3600, 'JINN', 'https://maps.google.com/maps/contrib/109529946471151847156', 0, true
from places where slug = 'banh-xeo-46a';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJOwpR9U0vdTER7VWboFERAEk/photos/AWCwydjSEgR_RuhyOBt3fPe1PmO7lucZ-bYXymH5YI38QKcYfw9npHWShPLKAh6iRIdSMq_S-F4Ilgf--FgopRrJv5tyeTrhJXbq0YAMvTRedh13zv8fgBTHfq9Q4KbNOwJTaXx7RUs9Fz1el4YqAntnG2YONnU-d_hG5hP6tdFXPTocbQ6U995pv9Oz27GUlotKXbtEu3yDNs7KQOK0jwyxTapcsb2yAnW4yJcLRhhebKlDvGyqNTTtxAxmhCvMhLyXEgzqlLDuTf5i67dP_FRlYp5QiHrf81Of7wngGfbCLksz3Wfh-QlWhPPY_L6J_fvJcOIAHTBDhYwMLDILwvlJZUbAHMbLpzIxyfBYBly9R-2YoWUrbURedUqP7W1hJjemb_E6b_jkaBFw7McR0RCkgDqskoDi6IAPlq0JOq01MUlc-se8', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDo1L2-9SfW7P6RtQ87Ynw2ZeZUH0QRgzK_8AAquCfVpPXyFKKDIZ9tljH0Ye57XDK1_8zO2BmCk7a7xYKUm7T33daL6gKnQe-9nyOyHpzPVNhWI07rAancJh-YCnBogmK8SVQ2TGtOzt4L_qA=s4800-w800', 4032, 3024, 'Bánh Xèo 46A', 'https://maps.google.com/maps/contrib/118234762988822738721', 1, false
from places where slug = 'banh-xeo-46a';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJOwpR9U0vdTER7VWboFERAEk/photos/AWCwydj-RztadnRpodtOmqdtxAiHPdM9gl4UZiqRcsp4-BP5NujQV08vC9IdRh_6bpTp-wPWZZeVtDL2TLdr11SPoNKzND2WYQr5MJAMn8aQNjzlc6OafgeXajNkKj3RiBK0wCJGWeAchoNfHrk674DkaTdSmNIAzEFEauoVGGao5n3SMOa2veOCYtNPqWEfGgM3ANK3RKvErb-EsZez5HJk6TSQXFUSyXwBAiR-hMLPAUOn5DF2KI4hTMJaQ2DqFlatZ8I2yTbR4Y18LjpNiUVyCSLURhwoBSGzYnOMThalYMhCZqYoDEzE0bVSTgZh08okbSvnAOrROSrDsJNRSLu4QNh4w1_WfDUMLLlNWVgFjusKXQtsd-5KKjfWJm-7jH5ZTh0AD_GoyZ_LMwiu_BoeigvL2-9dw67WPje8THQHgsZdFZIhkaqCWXjgN9dCni4o', 'https://lh3.googleusercontent.com/place-photos/AG9NLjDFT7qlxiAxGFJ9ibBQrioBBL7zpPcxKOjD5019xUxD8QBchrT8wriKz6atGHWvWeOqZj6zr33-hkfMvZHPTe0EqmrQwd41NfeWUNfrjxVIl8evkxQJ1j0X4aHCtHkazXCY6wvE1o8W6nlAUERDMwrDOA=s4800-w800', 4284, 4284, 'Tài Lê', 'https://maps.google.com/maps/contrib/100492667426498836214', 2, false
from places where slug = 'banh-xeo-46a';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('oc-dao', 'ChIJW2SKwawvdTERC3i1B0RZSHs', 'Ốc Đào', 'Ốc Đào', 'food', false, array['food_tour']::text[],
  'Nguyễn Trãi, D1', 'Nguyễn Trãi, Q1', '212B/D48 Nguyễn Trãi, Cầu Ông Lãnh, Hồ Chí Minh, Vietnam', 10.765238, 106.6846346, 4.2, 2392,
  'PRICE_LEVEL_MODERATE', '150k₫', 150000, 60, 90,
  'The snail-eating institution hidden in a D1 alley — order garlic-butter scallops and salted-egg snails for the table.', 'Địa chỉ ăn ốc huyền thoại trong hẻm Quận 1 — gọi sò điệp bơ tỏi và ốc trứng muối cho cả bàn.', '🦪', '["Monday: 11:00 AM – 10:15 PM","Tuesday: 11:00 AM – 10:15 PM","Wednesday: 11:00 AM – 10:15 PM","Thursday: 11:00 AM – 10:15 PM","Friday: 11:00 AM – 10:15 PM","Saturday: 11:00 AM – 10:15 PM","Sunday: 11:00 AM – 10:15 PM"]'::jsonb, 'https://ocdaonguyentrai.com/', '+84 909 437 033', 4, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();

delete from place_photos where place_id = (select id from places where slug = 'oc-dao');
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJW2SKwawvdTERC3i1B0RZSHs/photos/AWCwydinIOOCMycP95WUublLYWH0TFBQ70StebP9vDQTjyTnEIydJzCwDvWLsFibROjWoUBZ6H3ynCR9HJkHzfzweOt362CLUxSNkIfIGaTHHj8rbt_pb5U906htMWUQ60iT9HsSpIap3qFXcknVNBk0cQs9qL_VGi8Olg5jtlrYjjtSRRjMgoA5swBF6stT1G07ABcqpr1AexWdFHWwL5XnK33yK9TrkKYPp1Yd5_ZJWIKHiC-mAyaBxJeh8PE5CoUXJisjUeDMOiX2DFejh-tog_9zSsG8cLudblqg2XDxK0hmBwj-5RJCQbfA0xPq4nfYISLJ3icyyN4mwLgqKfIUzVklyv8gJH7dTBmijOL_3ONWpsepgnHwhT3qnIGAAF585cEghT6W2ysf1ZifoY1j8muODvNGpW8kgbD-CmoSfrPotA', 'https://lh3.googleusercontent.com/place-photos/AG9NLjCzScI0gSgf-0HtSn4bSkTFhA9vJ85XcyPwFPgwXEf0JSkMg_x-Tfs7qk0pacGU81e91kZ9sFySY_YfV-rc6P66lcAt_Ue-4ftGhy4Uawu0txw47p2T3H65R3C2FYH2dIdEMTQ0nbUyy-wXLQ=s4800-w800', 4032, 3024, 'xuyen Mai', 'https://maps.google.com/maps/contrib/101547126081097322955', 0, true
from places where slug = 'oc-dao';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJW2SKwawvdTERC3i1B0RZSHs/photos/AWCwydhr2d1nMqTNjh3M_fjDIulpbUgeClCehqiJ5WjuCoaR4MDpB3ib32NR2DBDYTMdZiKhQL4bZJqBLHLa7AmdB4ppis-uDo3WguMj-M5BlAs7jTdvj6FYUo5sU0x80FGJT3hb66xtLingDKw_moTXZBY5Yluea2cq-KcHUe7Egzm6ffAbJSfYzXSXmjDoBuG3lm6SinXNekdypwfdOlkw7GmdEyf8p9zR8jKiB7wP6htDGec8R_SlA__3O0FysCDJFAm9bleEz_xqzIxRZoRTw8OBFt05SXMC4A_NGTlbsA01Dk1PLzgp2pHzqZDDxhXSnV5d6PzfWFXrGSwBAsU3nIf41e8BeHm2Bhtuph5l8zy0aLgvsFKBMnCRxSPJoews1YAS7Bo_LEkBmtxk6r_895zV4uMNis7L16X5waKJBLQASuu4k5R_F6CnbCoHzg', 'https://lh3.googleusercontent.com/place-photos/AG9NLjA2RzH9tcYGhW2034noayN3wXax_Khq3ueY9DlWgixS_SBRrsqTFBUqDLNn5Bu44jnmNb00q3I_meN6I8DLxDpOQXOnz28Dxj0_FJ1le2BJFYlJmdokrHj6JHLbNdJTKFGwawJstksemwrJom2XH2US=s4800-w800', 4032, 3024, 'yuichi sasaki', 'https://maps.google.com/maps/contrib/103660962830515051392', 1, false
from places where slug = 'oc-dao';
insert into place_photos (place_id, photo_ref, photo_uri, width_px, height_px, attribution_name, attribution_uri, sort_order, is_cover)
select id, 'places/ChIJW2SKwawvdTERC3i1B0RZSHs/photos/AWCwydi0Wgg6Q1uFFgE6kQL8rDlsB58oXbjAM2noawcAw0hEmZxMKo4H_NPL7j2JwVL4xK7ofYB0smjr343zXjdMkhpWhtl4qLM6tEcpNuC0N__fhA1jGmWSCB3NUocJkPctGqbej-IMBt-FPTQvOHGnY8oXN5i9mGbI041mXl_MUoRg6RzvvTh9yJIqXU79lbPIWVXakPeZiuOGje3M3r6wfjHoCWN_1NwLEtF4VNIw8dIbNpyCRpKElHrx6xP1zor5htIN-T7D9GW38ATRuns8sjNl7vUXlh59jLgGBzdeGJ29eO-6ktpXT9E-MOfG0_L53cn6dij1FIV5Lp4pMlHrfI0EkhenErJ0R_0GCLHM4y4xQdzMSABWmjA8xJo0olCBrok8aRPTiz6OeL3CjdiUnZHNmmFU2IcBZ-MdA31Lq7oeTq-QfZmDPDp9Xj_XkQ', 'https://lh3.googleusercontent.com/place-photos/AG9NLjAol8XijvCx7ePx1PWOLV8IjXScIe435qwKRcx_w4mVpWokRDuTm_P0d_FpxjoO4BHG6X21YtxF_j_SpJXGRmIrh0R2luZEKhh965xf5uubrzwzym0mvl0UDLH-HaoSN4m1XkODzvidofwEg8sBvwY_=s4800-w800', 4000, 2252, 'Kittika P', 'https://maps.google.com/maps/contrib/112350913824706268840', 2, false
from places where slug = 'oc-dao';

insert into places (slug, google_place_id, name_en, name_vi, category, is_featured, vibe_tags,
  neighborhood_en, neighborhood_vi, address, lat, lng, rating, rating_count,
  price_level, price_display, price_vnd, duration_min, duration_max,
  desc_en, desc_vi, emoji, opening_hours, website, phone, saved_count, is_published, updated_at)
values ('ho-thi-ky-food-street', 'ChIJB9fPdQgvdTERisLWl4TFuK8', 'Hồ Thị Kỷ food street', 'Phố ẩm thực Hồ Thị Kỷ', 'food', false, array['food_tour','nightlife']::text[],
  'District 10', 'Quận 10', 'Hồ Thị Kỷ, Vườn Lài, Hồ Chí Minh 70350, Vietnam', 10.7663259, 106.6759953, 4.4, 3797,
  null, '120k₫', 120000, 90, 120,
  'Flower market by day, packed food alley by night — Cambodian desserts, grilled everything, all under 50k a dish.', 'Chợ hoa ban ngày, hẻm ăn vặt chật kín ban đêm — chè Campuchia, đồ nướng đủ loại, món nào cũng dưới 50k.', '🍢', '["Monday: 5:00 – 10:00 PM","Tuesday: 5:00 – 10:00 PM","Wednesday: 5:00 – 10:00 PM","Thursday: 5:00 – 10:00 PM","Friday: 5:00 – 10:00 PM","Saturday: 5:00 – 10:00 PM","Sunday: 5:00 – 10:00 PM"]'::jsonb, null, null, 4, true, now())
on conflict (slug) do update set
  google_place_id = excluded.google_place_id, name_en = excluded.name_en, name_vi = excluded.name_vi,
  category = excluded.category, is_featured = excluded.is_featured, vibe_tags = excluded.vibe_tags,
  neighborhood_en = excluded.neighborhood_en, neighborhood_vi = excluded.neighborhood_vi, address = excluded.address,
  lat = excluded.lat, lng = excluded.lng, rating = excluded.rating, rating_count = excluded.rating_count,
  price_level = excluded.price_level, price_display = excluded.price_display, price_vnd = excluded.price_vnd,
  duration_min = excluded.duration_min, duration_max = excluded.duration_max,
  desc_en = excluded.desc_en, desc_vi = excluded.desc_vi, emoji = excluded.emoji,
  opening_hours = excluded.opening_hours, website = excluded.website, phone = excluded.phone,
  saved_count = excluded.saved_count, is_published = true, updated_at = now();