// The lint gate. Typecheck answers "do the types line up"; this answers the
// questions TypeScript structurally cannot — a hook called conditionally, a
// dependency array that has gone stale, an import that resolves to nothing.
//
// It was added to a codebase that had never been linted, so the first run
// was a measurement rather than a verdict: 26,000 lines of TS/TSX produced
// 48 findings, and reading all of them found no bug. Every one of the 24
// `exhaustive-deps` reports was the same deliberate idiom — see below. That
// is worth writing down, because it sets what this gate is *for*: not
// cleaning up a mess, but noticing the next one.
//
// ── the one idiom this rule cannot verify ──
//
// The hooks here depend on the stable *field*, not the unstable object:
//
//   const fetcher = useCallback(() => fetchPlaces(city.id, meId), [city?.id, meId]);
//
// `city` is a fresh object most renders; `city.id` is not. Depending on
// `city` would refetch the whole catalog on renders where nothing about the
// city changed. The rule sees `city` used in the body, cannot prove the body
// only reads `.id`, and asks for the object. The narrower array is correct
// and the rule is wrong, so those sites carry an inline disable with the
// reason on it. Same shape for `mine.reload` over `mine`, `me?.lat`/`me?.lng`
// over `me`, `places.data`/`places.loading` over `places`.
//
// The disables are per-site and each says why, rather than the rule being
// switched off, because the moment it is off it stops catching the case it
// exists for: a dependency someone genuinely forgot.
//
// ── severity ──
//
// Everything is an error and CI runs `--max-warnings=0`. A warning that
// nobody has to act on is the decorative gate `vitest.config.ts` argues
// against at length; there is no third state between "this may land" and
// "this may not".

const expo = require('eslint-config-expo/flat');
const prettier = require('eslint-config-prettier');

module.exports = [
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      'coverage/**',
      // Generated by expo prebuild; not ours to lint.
      'android/**',
      'ios/**',
    ],
  },

  ...expo,

  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    linterOptions: {
      // A disable comment that no longer suppresses anything is a note about
      // a problem that has been fixed, left where it reads as one that has
      // not. Three were already in the tree when this landed.
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      // The two that catch crashes rather than untidiness. `rules-of-hooks`
      // has no false-positive mode worth tolerating: a hook behind a
      // condition is a runtime fault, always.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',

      'import/first': 'error',
      'import/no-duplicates': 'error',
    },
  },

  // `@typescript-eslint` is only registered for the TypeScript files, so its
  // rules have to be asked for where the plugin is in scope.
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // `_`-prefixed is the established way to say "bound on purpose, unused
      // on purpose" — the rest-destructure that drops one key in
      // `catalog.tsx` needs it.
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],
    },
  },

  // Test files hoist `vi.mock` above their imports on purpose: the factory
  // has to be registered before the module under test is pulled in, so
  // `import/first` is asking for the one order that does not work.
  {
    files: ['**/*.test.ts', '**/*.test.tsx'],
    rules: { 'import/first': 'off' },
  },

  // Last, so it wins: turns off every rule that would argue with the
  // formatter. Nothing here formats today (see ../prettier.config.cjs), but
  // the day a reformat is decided on, the two must not fight.
  prettier,
];
